### ISSUE TITLE
Removing the line in condensed icon note page break

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1933] opened 2020-02-19 17:55 UTC
# What happened?
When there is a page break within a condensed icon note this happens:

![image](https://user-images.githubusercontent.com/11299125/74856350-9b15e000-5307-11ea-8465-fb95fa05474c.png)
This is in HS Physics chapter 2.1 page 75. 

<img width="872" alt="Screen Shot 2020-02-19 at 11 52 48 AM" src="https://user-images.githubusercontent.com/11299125/74860504-622d3980-530e-11ea-8886-d6e7a17cd787.png">
This one is fro College Physics chapter 2.8

Is it possible to remove that line that occurs on the bottom of the page at the page break? It is functioning correctly for examples and the not condensed icon note/regular icon note so I assume it is possible.

# Acceptance criteria
Here is an example of it functioning correctly in a regular icon note. Taken from Biology
<img width="455" alt="Screen Shot 2020-02-19 at 11 55 13 AM" src="https://user-images.githubusercontent.com/11299125/74860727-be905900-530e-11ea-83c4-1a96e405efd8.png">

**Comment by helenemccarron** [comment] 2020-02-19 19:46
Spec update: add `box-decoration-break: slice,` l.299  and l.303 in the CondensedContainer


HS physics:
![2020-02-19_13-38-00](https://user-images.githubusercontent.com/8514591/74869341-6876e200-531d-11ea-872a-339d2b9bbd9d.png)

**Comment by helenemccarron** [comment] 2020-02-19 20:06
(I know the images are missing, somehow they didn't get pulled)

**Comment by helenemccarron** [comment] 2020-02-20 15:26
Also fixes https://github.com/openstax/cnx-recipes/issues/1936 (which I think might be a duplicate of this)

**Comment by MartaSztuka** [comment] 2020-02-24 10:20
Still occurs.
![Screenshot from 2020-02-24 11-19-46](https://user-images.githubusercontent.com/47241114/75144626-9c744d80-56f7-11ea-930e-069b74292e31.png)

**Comment by openstaxalina** [comment] 2020-02-24 22:09
Here is another place this should be tested (in Biology 2e - caught in Symmetry review)
![Screen Shot 2020-02-24 at 4.08.40 PM.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/7d5f732d-b1c5-457f-832a-d70ac3b2526d)

**Comment by openstaxalina** [comment] 2020-02-24 22:15
And another flagged in Symmetry's review:
![Screen Shot 2020-02-24 at 4.15.17 PM.png](https://images.zenhubusercontent.com/5b57372fb01a900cfd923015/805e295c-7df1-4509-9242-cfe2936210a1)

**Comment by helenemccarron** [comment] 2020-02-25 21:58
![2020-02-25_15-57-41](https://user-images.githubusercontent.com/8514591/75291330-9b224e00-57e7-11ea-87ce-a48a769f60fc.png)
The link to learning notes in biology 2e should now be working as intended.

**Comment by helenemccarron** [comment] 2020-02-26 17:39
PR #1963 fixes links to learning in biology specifically. A specs update is needed. Please add l.330: `box-decoration-break: slice, `

**Comment by MartaSztuka** [comment] 2020-02-28 16:24
College Physics - there's still this line
![Screenshot from 2020-02-28 17-13-51](https://user-images.githubusercontent.com/47241114/75565166-c7d79f00-5a4d-11ea-9da6-9a7d5a54a4b5.png)
Biology 2e - line is removed
![Screenshot from 2020-02-28 16-58-41](https://user-images.githubusercontent.com/47241114/75564152-e5a40480-5a4b-11ea-9aa4-ca6ba7274dd6.png)
HS Physics
![Screenshot from 2020-02-28 17-22-43](https://user-images.githubusercontent.com/47241114/75565852-002bad00-5a4f-11ea-80e3-3ed2999b378d.png)

**Comment by helenemccarron** [comment] 2020-03-02 17:20
@MartaSztuka  College Physics, tested on master. This seems to be working?![2020-03-02_11-15-06.png](https://images.zenhubusercontent.com/5b06d3244b5806bc2bd47abf/4dafcf7b-6a3b-4463-bf61-092a16743693)

and I believe HS physics is working as intended (the bar doesn't appear).

**Comment by MartaSztuka** [comment] 2020-03-03 10:40
@helenemccarron As for HS Physics it is correct. But I've tested College Physics both on current branch (f.f) and master, line is still there. Fetched this morning (~11am). By the way did you notice there is no picture on your screen? I wonder why.
![Screenshot from 2020-03-03 10-28-20](https://user-images.githubusercontent.com/47241114/75761767-eaadd000-5d39-11ea-826f-3faa6e64cedd.png)

**Comment by brittweinstein** [comment] 2020-03-09 14:38
@Stackblocks will try to replicate this.

**Comment by Stackblocks** [comment] 2020-03-09 17:02
@helenemccarron When I fetched the latest version of branch `issue-1933` and built the PDF using the full docker-compose steps for consistency I also get the result that Marta is getting. Is all of the development code pushed to the branch? 

![image](https://user-images.githubusercontent.com/12678235/76238357-bcc70080-61fd-11ea-9756-fcdd31a5170c.png)

**Comment by helenemccarron** [comment] 2020-03-09 19:02
Indeed, thank you both. I will create another PR to fix it. I have added the property everywhere in the components where a border is defined. Hopefully, this will take care of __all__ the cases 😓 
![2020-03-09_14-00-12](https://user-images.githubusercontent.com/8514591/76248083-a4abad00-620e-11ea-9189-1f163d266dc6.png)

**Comment by helenemccarron** [comment] 2020-03-11 19:22
the changes have been merged to feathered.fabio and ready to test, @MartaSztuka

**Comment by MartaSztuka** [comment] 2020-03-12 11:57
College Physics![Screenshot from 2020-03-12 12-56-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5294f0df-be72-4ff5-a77c-55fe2c538e71)

**Closed by MartaSztuka** 2020-03-12 11:57 UTC
Labels: baked.styles, book:biology.2e, book:college.physics, book:physics
