### ISSUE TITLE
College Success: Table Heading is not aligned as center

### ISSUE THREAD

**Issue by clteam18** [openstax/cnx-recipes#1631] opened 2019-11-22 13:25 UTC
- **Book(s)**: College Success
- **URL/Server**: https://content03.cnx.org/contents/X95lCXNn@3.1:93LeJ_RW@1/The-Benefits-of-Time-Management
- **Location (page number, chapter/section)**: Chapter 03/m10093
- **Suggested nearby searchable text**: Measured by the financial cost to you,

# Screenshots

![image](https://user-images.githubusercontent.com/39794953/69429365-61115e00-0d59-11ea-8fb5-9b71afec9381.png)

# Additional notes

We have used align="center" for all the table headings. But not aligned as center. Please check and advise

**Comment by openstaxalina** [comment] 2019-11-22 19:20
@yblock please review the markup.  My guess is that the table needs class=`top-titled` and for the title to be in a header row (???).

**Comment by yblock** [comment] 2019-11-22 20:26
This was another issue that was caused by the recipe not being applied to the collection. After the recipe was applied the title is centered and looks correct online.

**Comment by yblock** [comment] 2019-11-22 20:29
@clteam18 Please confirm and close the issue if resolved.

**Closed** 2019-11-28 14:29 UTC
Labels: book:college.success
