### ISSUE TITLE
corn - precal/precal-coreq - exercises spilling over margins in EOS

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2761] opened 2020-09-09 23:08 UTC
![Screen Shot 2020-09-09 at 1 49 38 PM](https://user-images.githubusercontent.com/11299125/92663493-113f5b80-f2c7-11ea-8f35-e0a84d298bd3.png)
![Screen Shot 2020-09-09 at 1 42 04 PM](https://user-images.githubusercontent.com/11299125/92663494-11d7f200-f2c7-11ea-9c22-61d83cbba31b.png)

This is in College Algebra/College Algebra Coreq - 4.2 Modeling with Linear Functions; 3.4 Composition of Functions

I think it might be because there's a list nested in it? Is it related to #2758 ?

**Comment by wilkus27** [comment] 2020-09-18 12:13
This problem is veeery weird... :confused:  I can't find what is causing this. 

Here is the screenshot from **college-algebra-coreq** with the newest content from katalyst01:

![image](https://user-images.githubusercontent.com/40228854/93590873-986b8e00-f9af-11ea-90d9-e0e587089318.png)

Here exercise 122 jump to the next line.

This screenshot is from **college-algebra:** (I have older content)

![image](https://user-images.githubusercontent.com/40228854/93590986-c781ff80-f9af-11ea-95b1-57055043a61e.png)


#### Another example

College algebra (old content)

![image](https://user-images.githubusercontent.com/40228854/93591164-25164c00-f9b0-11ea-9302-d7418cf5e528.png)

College Algebra Coreq (new content)

![image](https://user-images.githubusercontent.com/40228854/93591220-395a4900-f9b0-11ea-90db-b7141df182d2.png)


#### Another example

Here is the example from one book (College Algebra - new content 3.4 SECTION EXERCISES):

![image](https://user-images.githubusercontent.com/40228854/93595445-0caa2f80-f9b8-11ea-849b-f5d180bebb68.png)

Exercises on the top are almost the same, they have paragraphs with math and circled lists inside.  :eyes: 

@Stackblocks @ajluk do you have any ideas what is going on here? :laughing: I think it might be content issue. It might depend on the way of adding math to the paragraphs. But it's just my assumption. :thinking: What do you think?

**Comment by ajluk** [comment] 2020-09-18 15:41
@wilkus27 As we already discussed this issue I will add below the conclusions for @Stackblocks to look into them as well:

This problem may be related to `circled lists` nested in the `problem container` and the way they are styled and break.
Here the solution worth trying could be decreasing the `padding-right` set for the `li` so maybe then the lists will break differently and take less space.
The other rather more complicated solution is to add a container (`span`) outside the `li` text node (so then both the token and the text will be in separate containers inside the `li`) via recipes and then try `display: flex` on `li`
I have one more idea to change `display` for the `ol` to `inline-table`  and also change `display` to `inline-table` or `table-row` to `li`.

**Comment by wilkus27** [comment] 2020-09-22 13:09
Update: I tried to remove styles from lists and as we predicted exercise 20 from above screenshot displays correctly:

![image](https://user-images.githubusercontent.com/40228854/93886099-4e531700-fce5-11ea-9c3a-df2f7846a632.png)

So the problem is in lists. I will try to find which property should be changed.

**Comment by ajluk** [comment] 2020-09-25 17:28
@MartaSztuka >> Information for testing purposes:
 EOS exercises columns shoud be tested in one book from every series: dev-math (f.ex. Prealgebra 2e, Elementary Algebra...), precalculus-coreq (College Algebra Coreq), calculus (Calculus vol 1 or 2, 3).

**Comment by MartaSztuka** [comment] 2020-10-21 15:27
## PASSED
### College Algebra coreq
#### EoS Exercises
1.![Screenshot from 2020-10-21 16-14-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e0a78ef5-d5e5-42df-9baf-ff89f59cb2e3)
2.![Screenshot from 2020-10-21 16-15-44.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/41f24787-850d-46dc-a624-8e8df2cd43ea)
3.![Screenshot from 2020-10-21 16-18-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ed3f4873-be00-4a38-bfe0-d5f91e953242)

**Comment by MartaSztuka** [comment] 2020-10-21 15:32
## PASSED
### Elementary Algebra
#### EoS Exercises![Screenshot from 2020-10-21 17-30-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/75f43d52-13a7-4ae9-9077-c2d85c38671e)

**Comment by MartaSztuka** [comment] 2020-10-21 15:34
## PASSED
### Calculus 2
#### EoS Exercises![Screenshot from 2020-10-21 17-33-49.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c6ec18ec-fd5f-44a3-acaf-7eaa46f18949)

**Closed by MartaSztuka** 2020-10-21 15:34 UTC
Labels: book:college.algebra, book:collegealgebra.coreq, book:precalculus, theme:corn
