### ISSUE TITLE
Math too Bold Bug

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1598] opened 2019-11-14 22:45 UTC
# Scenario
Math in carnival theme is too bold (not technically, like there are bold bits that are even bolder, but the font is too heavy).
# Steps to Reproduce

* **How many times were you able to reproduce the issue?** 

* **Images or Screenshots Included:** [ ] Yes  [ ] No  (_attach below_)

# Environment:

* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org  
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact

* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan 

# Acceptance Criteria

**Comment by openstaxalina** [comment] 2019-11-26 15:05
Here is a screenshot from Biology 2e, section 6.4:
![image (5)](https://user-images.githubusercontent.com/7863733/69645454-d0be6c00-102b-11ea-96ab-4a6b0811fc07.png)

**Comment by brittweinstein** [comment] 2019-12-09 15:43
@helenemccarron will discuss with Piotr.

**Comment by helenemccarron** [comment] 2020-01-08 22:55
I think I have a solution :D leaving this here for testing later. 
![2020-01-08_15-48-19](https://user-images.githubusercontent.com/8514591/72023160-b802c200-3237-11ea-90b5-589712e0f7af.png)

**Comment by openstaxalina** [comment] 2020-01-09 16:58
Larissa confirmed display is acceptable.

**Comment by marcjeannott** [comment] 2020-01-22 15:28
Verified the math is less bold using cops on staging... the spacing seems wrong though. I imagine it'd have a line break after the equation as well.  ![2020-01-22_09-26-54.png](https://images.zenhubusercontent.com/5b572d7e0e34d640605a661c/f5ff8efa-98e5-4658-a186-d40e8d8d357e)

**Comment by openstaxalina** [comment] 2020-01-22 15:41
Agree that the bolding is gone 🎉 

In the oer.exports PDF we had spacing above and below the equation;  also the equation was centered:
<img width="520" alt="Screen Shot 2020-01-22 at 9 39 16 AM" src="https://user-images.githubusercontent.com/7863733/72908495-28f7ae80-3cfb-11ea-80af-9ef518b60709.png">

@helenemccarron I know this issue is about bold math, but do you know why the equation would now be left-aligned and have lost the space below it?  (Should we open another issue for that?)  cc @lwtchu @brittweinstein

**Comment by brittweinstein** [comment] 2020-01-24 14:56
@openstaxalina I've opened another issue to track the spacing issue. Here is the new issue: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1809 please prioritize when you can! I will close this issue since its original intent has been served!

**Closed by brittweinstein** 2020-01-24 14:56 UTC
Labels: book:biology.2e, type:bug
