### ISSUE TITLE
Astronomy - Examples 

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#3089] opened 2020-11-24 17:31 UTC
Should follow https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2899

**Comment by ajluk** [comment] 2020-12-30 08:09
@brittweinstein This is a duplicate of  #3028

**Closed** 2021-01-06 15:47 UTC
Labels: book:astronomy
