### ISSUE TITLE
[HOLDING until requirements are clear] Comprehensive approach to units in BakedStyles

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#943] opened 2019-03-14 21:23 UTC
Units should work for both the PDF and Unified

**Comment by openstaxalina** [comment] 2019-04-23 17:20
Holding until we determine whether we are using Root Element Line Height (REM) to designate everything.  Probably won't be able to finish this until we start implementing styles.

**Comment by brittweinstein** [comment] 2019-12-05 18:18
@openstaxalina has there been a decision here?

**Comment by openstaxalina** [comment] 2019-12-06 22:20
@brittweinstein, yes, I think so.

I had noted above: Holding until we determine whether we are using Root Element Line Height (REM) to designate everything. Probably won't be able to finish this until we start implementing styles.

Since we have the font scale, can we close this @helenemccarron @lwtchu ?  Or is there more work to do to support units? I saw them in the A&P PDF that is in regression testing...

**Comment by helenemccarron** [comment] 2020-02-06 19:07
From a font-size perspective, this can be closed. From a design and specs perspective, I know there were some questions about the TOC but that's in a different issue, I believe.

**Comment by openstaxalina** [comment] 2020-02-06 19:10
Yep we have https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1782

So I'm closing this!

**Closed by openstaxalina** 2020-02-06 19:10 UTC
Labels: baked.styles
