### ISSUE TITLE
Punctuation marks

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2080] opened 2020-03-24 10:18 UTC
@helenemccarron @brittweinstein @lwtchu Commas and periods drop to another line sometimes.
![Screenshot from 2020-03-24 10-15-46](https://user-images.githubusercontent.com/47241114/77414274-08aea380-6dc1-11ea-997b-9c521f316067.png)
![Screenshot from 2020-03-24 10-17-43](https://user-images.githubusercontent.com/47241114/77414277-09dfd080-6dc1-11ea-9fd6-d2205bcd4e83.png)

**Comment by helenemccarron** [comment] 2020-03-24 13:54
I think that's a duplicate of #1981

**Comment by Stackblocks** [comment] 2020-03-24 13:54
If I recall correctly this is happening when the punctuation follows an SVG because that doesn't count as a "word" for the punctuation to stick with instead of breaking.

**Comment by brittweinstein** [comment] 2020-03-24 14:43
we will close this as it is a duplicate, as noted above.

**Closed by brittweinstein** 2020-03-24 14:43 UTC
Labels: baked.styles, book:college.physics, regression.testing
