### ISSUE TITLE
Enable multiple indices types

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1010] opened 2019-04-15 15:46 UTC
The Polish recipe for University Physics needs more than one kind of Index: names index, foreign terms, etc. in addition to our current terms. 

This would be a useful feature for all recipes and should be integrated in our code base. The current work for it has been started here: https://github.com/openstax/cnx-recipes/pull/377/files

It should be extracted and combined with the recipes to enable multiple indices for all books.

**Comment by openstaxalina** [comment] 2019-04-16 15:05
Per @helenemccarron, Katalyst is using the namespace to select which term goes into which index.  @aiwenar how did you specify which index a term goes to?  Is it in the markup?

The test plan likely includes regression testing on the Index across all OpenStax and Katalyst titles, as well as some community-created content.

**Comment by MartaSztuka** [comment] 2019-04-29 12:31
https://katalyst01.cnx.org/contents/TqqPA4io@1.98:JXYkqYBo@1.98/Index-of-names
https://cnx.org/contents/TqqPA4io@1.134:JXYkqYBo@1.134/Skorowidz-nazwisk

![fiz](https://user-images.githubusercontent.com/47241114/56896140-40b34680-6a8b-11e9-8982-5fb077fde7f2.jpeg)

Probably this should be unified.

**Comment by MartaSztuka** [comment] 2019-04-29 12:40
https://katalyst01.cnx.org/contents/TqqPA4io@1.98:lyD6ZIjV@1.98/Index-of-terms
https://cnx.org/contents/TqqPA4io@1.134:lyD6ZIjV@1.134/Skorowidz-rzeczowy
![fizpol2](https://user-images.githubusercontent.com/47241114/56896681-b0760100-6a8c-11e9-8aa4-a54f4f521829.jpeg)

**Comment by openstaxalina** [comment] 2019-04-29 13:25
For the extra terms under "SYMBOLS" - when we saw this in English books it is because the term has a space in front of it.

For example, it may be: `<term> średnia moc<term>`.  
If you change it to `<term>średnia moc<term>` this may resolve the problem.

**Comment by openstaxalina** [comment] 2019-05-14 14:39
This is resolved with https://github.com/openstax/cnx-recipes/pull/1021, but we need a merging strategy.  Thomas, BrittanyJ, and Helene will review the PR and confirm this can be merged into master or the current Books milestone branch.

**Comment by brittweinstein** [comment] 2019-05-21 14:20
@aiwenar are we ready to merge this?

**Comment by paulinaszczucinska** [comment] 2019-05-21 15:41
Multiple indexes are created correctly. Regarding words in English in table of content (see screen above): they will be changed to Polish when book is baked with Polish recipe. As Krzysztof Mędrzycki says: "They are now in English as an example, but the fact itself that they are there means it's working (as those phrases don't exist in master)."

**Closed** 2019-06-07 16:21 UTC
Labels: book:fizyka
