### ISSUE TITLE
Math font regressions

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1882] opened 2020-02-07 17:01 UTC
# Scenario
HS Physics baked pdf does not italicize `mi` tags, does not include some characters. Markup is correct, but no `mi` tags are rendering as italicized, and some operators including approximately-equal-to are replaced with question marks.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="325" alt="Screen Shot 2020-02-07 at 10 57 50 AM" src="https://user-images.githubusercontent.com/1895432/74049181-38ccef00-4999-11ea-91e3-f3faa935503d.png">
<img width="475" alt="Screen Shot 2020-02-07 at 10 56 16 AM" src="https://user-images.githubusercontent.com/1895432/74049182-39fe1c00-4999-11ea-9e18-93e3a6bae2ad.png">

On legacy these characters are properly rendered:
<img width="671" alt="Screen Shot 2020-02-07 at 11 03 58 AM" src="https://user-images.githubusercontent.com/1895432/74049363-919c8780-4999-11ea-8c78-03e437e9b8af.png">
<img width="126" alt="Screen Shot 2020-02-07 at 11 03 02 AM" src="https://user-images.githubusercontent.com/1895432/74049366-92351e00-4999-11ea-9604-834611c44ecd.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by helenemccarron** [comment] 2020-02-10 22:14
@oscryan  I am not sure how the PDF was generated but after fetching HS phsyics, assembling it, mathifiying it and converting it into a PDF, here's what the same section looks like. 

![2020-02-10_16-10-04](https://user-images.githubusercontent.com/8514591/74195140-3c25dc00-4c20-11ea-94f1-cf71dc544cab.png)

Are we sure that the PDF is mathified? It also looks likes styles are wonky on the first screenshot.

**Comment by oscryan** [comment] 2020-02-10 22:16
the pdf came from here:  https://drive.google.com/drive/u/0/folders/1CnqMc7U2t7SqgQtrHnOQH-9HraZVrro7

**Comment by helenemccarron** [comment] 2020-02-10 22:17
For some reason, that link doesn't work.

**Comment by lwtchu** [comment] 2020-02-10 22:52
@helenemccarron it's in the katalyst channel - natalia generated at 9:36 on february 6

**Comment by helenemccarron** [comment] 2020-02-10 22:54
I don't think the book was mathified. I am trying to generate it as we speak but I am having issues with images. I'll keep you posted and provide the new PDF as soon as possible.

**Comment by helenemccarron** [comment] 2020-02-12 20:31
@lwtchu and @openstaxalina should we close this?

**Comment by openstaxalina** [comment] 2020-02-12 20:33
Yes, @oscryan confirmed that this was resolved on the newer, mathified PDF.  closing

**Closed by openstaxalina** 2020-02-12 20:33 UTC
Labels: book:physics, type:bug
