### ISSUE TITLE
HS Statistics - Example solution not styled

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2675] opened 2020-08-24 12:49 UTC
### Solution in Example is unstyled in random locations ![Screenshot from 2020-08-24 13-33-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66e82b45-113d-4a7b-8589-eff6a4d16357)![Screenshot from 2020-08-24 14-21-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f668ce6f-dbab-49a6-a6a1-8db3efc1d1b8)

**Comment by ajluk** [comment] 2020-08-25 13:44
@lwtchu This issue a duplicate of https://github.com/openstax/cnx-recipes/issues/2660 but it regards HS Physics instead. Here  content changes are needed that Natalia has written about here(https://github.com/openstax/cnx-recipes/issues/2660#issuecomment-679150838).
Here is how these examples look in the html file:
![image](https://user-images.githubusercontent.com/55203598/91181231-fa0a4680-e6e8-11ea-9bb5-7b4f672159e2.png)
![image](https://user-images.githubusercontent.com/55203598/91181695-89aff500-e6e9-11ea-9c6f-6b272dabc0ad.png)

**Comment by wilkus27** [comment] 2020-09-14 13:16
@lwtchu Changes maded in the code are already on master. They were tested in Intro Statistics. What do you recommend for this issue? Should we wait for a content changes or we can close it?

**Comment by lwtchu** [comment] 2020-09-14 17:35
@wilkus27 i think we can close. after the content fixes are done we can QA our fixes and open any issues as needed? (before any title goes to print we do a quick QA also to catch any lingering issues)

feel fere to re-open if you have concerns.

**Closed by lwtchu** 2020-09-14 17:35 UTC
Labels: book:hs.statistics, question:Larissa
