### ISSUE TITLE
HSPhysics Exercises appearing in the wrong places

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#1612] opened 2019-11-18 15:39 UTC
# What happened?
Exercises in hsphysics are appearing in the wrong places

# Environment:

- **Book(s)**: hsphysics
- **URL/Server**: https://content04.cnx.org/contents/IKZFuFtg@10.2:vOVpVdiV@2/1-1-Physics-Definitions-and-Applications

# Screenshots
Check Your Understanding PDF: 
![Screen Shot 2019-11-18 at 9.18.52 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/8cff672d-5fc0-4f8a-894e-2ab4dbe41f37)

Check Your Understanding web: 
![Screen Shot 2019-11-18 at 9.19.03 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/b470fc02-5747-4dca-9303-5b6bee56db2a)

Grasp Check PDF : 
![Screen Shot 2019-11-18 at 9.20.41 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/5b456e13-d1e9-49d9-a36b-b38e494ba04d)

Grasp Check web: 
![Screen Shot 2019-11-18 at 9.21.10 AM.png](https://images.zenhubusercontent.com/5b0d6efdd59b032fbd122962/864215ee-8e90-4631-9d80-6e72532171a5)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by wilkus27** [comment] 2019-12-20 09:00
This is caused by section **Problems** which has class `problem`. When section is moved to EOC, recipe creates container with class `os-classFromSection-container`, so in this case it's `os-problem-container`, but this is a class which occurs in all exercises, so that's why exercises from the entire book are moved to EOC. 

This will be resolved by changing name of the class for section **Problems** in content.

**Comment by openstaxalina** [comment] 2019-12-20 16:20
@oscryan changed the class to `problems` per conversation in Slack: https://openstax.slack.com/archives/CBW9DFKGF/p1576669322033600

**Comment by MartaSztuka** [comment] 2020-01-13 14:44
https://katalyst01.cnx.org/contents/qRkBHZVu@4.1:N8rgsfvo@3/16-3-Lenses
![Screenshot from 2020-01-13 15-43-48](https://user-images.githubusercontent.com/47241114/72264772-8e70de80-361b-11ea-934b-0cbbb50c2241.png)

**Closed by MartaSztuka** 2020-01-13 14:44 UTC
Labels: book:physics
