### ISSUE TITLE
table element alignment not consistent 

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#3482] opened 2021-02-08 17:31 UTC
# Brief Description of Scenario and Screenshots
What kind of issue is this? [ ] recipe [ ] styles [ ] both [ ] i don't know

![Screen Shot 2021-02-08 at 11.25.47 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/1f27b466-f33d-4aea-9e69-b2a35597de13)

https://openstax.org/books/microbiology/pages/17-1-physical-defenses#fs-id1172100638917

# Acceptance Criteria
LC: Can we make sure the padding is added to the cells even if there's a more rows attribute to the table?

# Bug Location(s)
collection ID: col12087
server: production
chapter/section: 17.1 
surrounding text: provides an overview of the nonspecific defenses

# Test Content Location(s)
(leave blank if the same as above)
collection ID:
server: 
chapter/section:
surrounding text:

**Comment by yblock** [comment] 2021-02-08 17:35
Possibly only happens when the "morerows" attribute is used on a an entry in CNXML to merge vertical cells.

**Comment by yblock** [comment] 2021-02-08 17:37
Here is an example of a table that is coded similarly where it is not happening. 
https://openstax.org/books/microbiology/pages/17-2-chemical-defenses#fs-id1172102098156

**Comment by MartaSztuka** [comment] 2021-02-25 09:41
@wilkus27 Tables look ok, but caption is unstyled![Screenshot from 2021-02-25 10-22-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/233f7490-0b02-4da8-a9ba-16e78bec3af9)

**Comment by wilkus27** [comment] 2021-02-25 11:44
@MartaSztuka I checked and I think it's ok. Here are specs for Carnival: https://github.com/openstax/cnx-recipes/issues/1080. Screenshot in description is from OER.export. @lwtchu can you confirm? :slightly_smiling_face:

**Comment by lwtchu** [comment] 2021-02-25 17:20
@wilkus27 i think the font for the table number should be muli black?

**Comment by wilkus27** [comment] 2021-02-26 13:08
Hmm I noticed two interesting things :smile: First, in carnival we don't specify font family for table caption anywhere. So it's inherited from the root ( it's `IBM Plex Serif`). Maybe it's a regression from some cleaning :thinking: I don't know. Maybe settings for captions were removed accidentally. Second, Muli font doesn't exist anymore on fonts google. It's changed to similar one Mulish: https://fonts.google.com/?query=muli&selection.family=Ovo&sidebar.open=true

![image](https://user-images.githubusercontent.com/40228854/109303768-8c77d800-783b-11eb-9f91-27db2367b9ef.png)

**Comment by lwtchu** [comment] 2021-02-26 20:36
@wilkus27 D: oh no. hm...should i make a card to replace muli with mulish?  it looks v similar.

**Comment by wilkus27** [comment] 2021-03-01 12:42
@lwtchu Yes, I think it's a good idea :+1: Maybe we should also create separate card for table caption :thinking:  What do you think? Then we can close this one, because it's related with alignment in tables cells.

**Comment by lwtchu** [comment] 2021-03-01 15:21
@wilkus27 mulish one: #3596 
caption: #3597 - i THINK it might impact university physics? if so i can add the label to this card

**Closed** 2021-03-05 11:57 UTC
Labels: book:microbiology, theme:carnival
