### ISSUE TITLE
Elementary Algebra - centers content in table

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2705] opened 2020-08-25 13:13 UTC
### Content in the last row should be left-aligned![Screenshot from 2020-08-25 12-26-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6cd7df2e-f443-4f76-a7b3-df87a9899719)

**Comment by wilkus27** [comment] 2020-08-26 15:35
@lwtchu It was centered because I didn't apply changes from #2637 to unnumbered unstyled tables. I fixed it in https://github.com/openstax/cnx-recipes/pull/2720. 

And as I checked this cell has attribute `[data-align="right"]`. I think it's ok because `21` is the result of addition `12+9` from previous cell. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/91324505-715fd900-e7c2-11ea-800c-30c96e8da86f.png)

**Comment by lwtchu** [comment] 2020-08-26 15:39
@wilkus27 yes that's how it's supposed to look thank you!

**Comment by meeragovindaraju** [comment] 2020-08-31 13:54
The last row looks as intended. But some of the surrounding font look different than the screenshot 👆  

![Screen Shot 2020-08-31 at 8 50 31 AM](https://user-images.githubusercontent.com/33066187/91727279-12ee7e00-eb67-11ea-9523-e601c5a89054.png)

**Comment by brittweinstein** [comment] 2020-08-31 14:32
@lwtchu could you confirm that this font is correct?

**Comment by brittweinstein** [comment] 2020-08-31 14:33
@meeragovindaraju will take a look at the font specificities here and provide more info.

**Comment by meeragovindaraju** [comment] 2020-08-31 15:05
The weird fonts are SVGs and are constructed by MathJax as part of the book process. @Stackblocks  will take a look at this

![Screen Shot 2020-08-31 at 9 55 10 AM](https://user-images.githubusercontent.com/33066187/91735118-71205e80-eb71-11ea-8ed0-4216e4442b47.png)

**Comment by lwtchu** [comment] 2020-08-31 15:25
That is an image not an SVG. I don't think it's an issue. If you feel comfortable, please close.

**Comment by meeragovindaraju** [comment] 2020-08-31 15:52
@lwtchu I am ok with closing it if you are ok with the font.

**Closed by meeragovindaraju** 2020-08-31 15:52 UTC
Labels: book:elementary.algebra.2e, prio:high
