### ISSUE TITLE
Fix tables in EoC

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1695] opened 2019-12-13 17:10 UTC
@MartaSztuka commented on [Fri Dec 13 2019](https://github.com/openstax/content-managers/issues/1293)

Tables in two-columns layout don't have enough space in cells, also other issues occurs.
![human](https://user-images.githubusercontent.com/47241114/70790371-3bdea100-1d95-11ea-80e3-eef15dcca30d.png)

**Comment by openstaxalina** [comment] 2019-12-13 17:11
@MartaSztuka I moved this issue to cnx-recipes.  I confirmed in the content that the row "Human" is intentionally left blank.  Therefore, I do not think there is a content issue to resolve here.  Please let me know if I misunderstood.

![Screen Shot 2019-12-13 at 11 06 38 AM](https://user-images.githubusercontent.com/7863733/70818430-4a2ebc00-1d99-11ea-8ba8-948ba7961d70.png)

**Comment by brittweinstein** [comment] 2019-12-16 16:07
@lwtchu @andymuddimer this is displaying accurately according to the specs. Do the specs need to be revised?

**Comment by lwtchu** [comment] 2019-12-16 16:47
@brittweinstein do you think we can make adjustments for this after regression testing so we can make changes that benefit all the titles in the theme?

**Comment by brittweinstein** [comment] 2020-01-13 15:36
@lwtchu let's go ahead and update the specs now so that when we do test against the spec, we can open issues per title. If the specs will change per book, we may need to reevaluate.

**Comment by openstaxalina** [comment] 2020-01-13 22:39
Currently this card requires no work because we haven't decided whether or how to change the styles.  If we do want to change the styles, we need to decide before the d.d. sprint.

**Comment by lwtchu** [comment] 2020-01-17 17:47
@helenemccarron is there a way to decrease the padding to 1.5px for all around using the h-grid? andy and i were looking at the specs adn we're not sure how to decrease past 8px

cc @andymuddimer

**Comment by brittweinstein** [comment] 2020-01-27 15:53
A scale for tables will be created (see: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1797).

**Comment by Stackblocks** [comment] 2020-02-04 17:24
@lwtchu Same as #1721, I believe primary work for this is resolved as part of #1791. Does the photo below look acceptable?

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/c251f880-00e4-479c-be5a-ba944e14f8db)

**Comment by lwtchu** [comment] 2020-02-04 17:36
oh that's nice. table numbering is..off should i open another issue for that

**Comment by Stackblocks** [comment] 2020-02-04 17:45
We can keep it in this one, and make that the primary focus. 🙃

**Comment by Stackblocks** [comment] 2020-02-04 17:52
Discussed with Larissa, the specific issue is that the figure number text is broken across two lines, not that the value is incorrect. This is similar to the figures in EoC breaking across multiple lines which was discussed in scrum, may need a broader investigation.

**Comment by Stackblocks** [comment] 2020-02-06 19:10
Hooking the caption component investigation into #1801 and closing this issue since the table styling work is separate/done.

**Closed by Stackblocks** 2020-02-06 19:10 UTC
Labels: book:ap.biology
