### ISSUE TITLE
Statistics - Unwanted space issue

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#5211] opened 2023-08-11 05:51 UTC
We have received the below feedback from customer. We didn't insert additional space in CNXML file. Kindly check and resolve this issue.

**"Fix formatting. Move Exercise 93 to this page."**

![Chapter9](https://github.com/openstax/cnx-recipes/assets/86622862/93478fd7-016b-4e3c-92f3-d0b3cca4e68e)

# Location(s)
- **osbooks repo:** https://github.com/openstax/osbooks-introductory-statistics-bundle
- **collection slug:** introductory-statistics-2e
- **ref/branch:** https://openstax-osbooksintrodu-rxj25jbp2zu.ws-us102.gitpod.io/
- **chapter/section:** Chapter 9/Chapter 5
- **surrounding text:** I could see that the cost varied but I had to sit down to figure out whether or not I was right.

**Comment by lwtchu** [comment] 2023-08-16 19:14
Duplicate of #5191. Closing.

**Closed by lwtchu** 2023-08-16 19:14 UTC
Labels: book:introductory.statistics
