### ISSUE TITLE
Answer Key structure

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#851] opened 2019-02-15 14:59 UTC
How this should be: 
1. Answer Key is in table of content before Index.
2. A.K. contains 2 sections: 'Try it Answers' & 'Odd answers'
3. 'Odd Answers' has also 2 subsections: (Review Exercise&Practice Test) ad the end of each chapter
![screenshot from 2019-02-21 15-30-38](https://user-images.githubusercontent.com/47241114/53176118-b0b9d200-35ed-11e9-80a4-06dcc3901087.png)
4. In PDF there is 'Try It Answers', in webview 'Answer Key', below 'chapter 1', and 'Try it'
![screenshot from 2019-02-21 15-41-13](https://user-images.githubusercontent.com/47241114/53176895-4bff7700-35ef-11e9-9721-3db9d5990809.png)

![screenshot from 2019-02-21 15-42-50](https://user-images.githubusercontent.com/47241114/53177019-8bc65e80-35ef-11e9-9ca6-74c0571fec28.png)

5. Try It Answers is devided to  headlines: 'Chapter #', and each Chapter contains 'Sections#.#'
6. Odd Answers is devided to the same way, and at the end there is 'Chapter # Review Exercise' and 'Chapter # Practice Test'
![screenshot from 2019-02-21 15-57-15](https://user-images.githubusercontent.com/47241114/53178044-663a5480-35f1-11e9-832c-0d816cca0238.png)
7. 'Try It Answers' refers to every question in chapter, however in 'Odd Answers' goes to every odd exercise number (1, 3, 5, 7, 9, etc.)

**Comment by Adrianltd** [comment] 2019-02-21 13:04
Duplicate of https://github.com/openstax/cnx-recipes/issues/857

**Closed** 2019-02-22 13:13 UTC
Labels: book:precalculus
