### ISSUE TITLE
HS Physics collating element with no content still shows header

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1885] opened 2020-02-07 17:29 UTC
# Scenario
When a chapter has no content tagged to a collating element, for example the Problems section, the header for it still shows up in the collated material for that chapter.

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="256" alt="Screen Shot 2020-02-07 at 11 27 21 AM" src="https://user-images.githubusercontent.com/1895432/74051096-f6a5ac80-499c-11ea-867c-2271f2dffd35.png">
<img width="261" alt="Screen Shot 2020-02-07 at 11 27 15 AM" src="https://user-images.githubusercontent.com/1895432/74051099-f7d6d980-499c-11ea-848d-fae990cc8e55.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by lwtchu** [comment] 2020-02-21 16:32
Content fix - chunks should have `problems`

**Comment by lwtchu** [comment] 2020-02-21 17:06
correlating: https://app.zenhub.com/workspaces/content-management-5c86d8c40b66e07993f45cfa/issues/openstax/content-managers/1463

**Comment by wilkus27** [comment] 2020-02-24 15:35
@openstaxalina @brittweinstein @helenemccarron Marta didn't find wrong classes in Chapter 22 and 23, so problem with empty header still will present. We need a recipe fix as well. 

@helenemccarron I think it will be a huge change. Similar problem occured in Astronomy: https://github.com/openstax/cnx-recipes/issues/658. Then you moved includes of mixins to different passes (https://github.com/openstax/cnx-recipes/pull/719/files). I guess that this problem has to be resolved in similar way. What probably will be very tricky and a lot of testing will be needed.

**Comment by openstaxalina** [comment] 2020-02-24 16:15
If this is going to be a huge amount of work, content managers may be able to fix this manually on these in the PDF in order to publish the book in March.  It looks like it's just two changes?  cc @helenemccarron @wilkus27 @lwtchu @paulinaszczucinska @brittweinstein

**Comment by wilkus27** [comment] 2020-02-25 08:47
@openstaxalina There are not all cases. Doing investigation I saw empty headers in other chapters. So we can find all instances in PDF, and then check in table created by @MartaSztuka https://docs.google.com/spreadsheets/d/1Gdwd8LiYHQxa4MG0MzdaWzzpN0ubJ4utTqyL9iqi2QI/edit#gid=0 which ones will be resolved by content, but I think that the best way is to wait until classes in content will be fixed and then test PDF to find all instances of empty headers.

**Comment by helenemccarron** [comment] 2020-02-26 23:58
@wilkus27  I think the issue is with l.334 through 347 in _compose.scss.

```      @if ($clusterBy == $CLUSTER_SECTION) {
        [data-type="page"] {
          &::after {
            class: "os-section-area";
            content: pending(#{$className}-separated);
            move-to: #{$className}-sectionSeparatedContainer;
          }
        }
        &::after {
          class: os-#{$className};
          content: pending(#{$className}-sectionSeparatedContainer);
          move-to: #{$className}-DESTINATION;
        }
      }
```
This is creating a container for the sections while going over each one of them before moving the content, filling it with an empty container regardless of the actual content. The container is then "non-empty" and not discarded when the actual content is moved to it. 

You were right that this is similar to the issue you posted. Somehow, we must extract the part that creates the inner container when clustering by section to a later pass so they empty containers remain empty. 

I have not yet reached the exact solution to this problem, let's talk about it on tomorrow's call.

**Comment by brittweinstein** [comment] 2020-03-23 14:43
We are able to fix this in the PDF so we will push this back to HH.

**Comment by brittweinstein** [comment] 2020-04-20 14:39
@wilkus27 you may have already started on this, not sure...I'm putting it in the backlog but feel free to move it to In Progress!

**Comment by wilkus27** [comment] 2020-05-11 10:34
@MartaSztuka this is a huge change and has impact on all books. I think it will be good to test Hs Physics and one other book by comparing PDFs generated with and without those changes.

**Comment by MartaSztuka** [comment] 2020-05-11 12:12
HS Physics
![Screenshot from 2020-05-11 13-55-59](https://user-images.githubusercontent.com/47241114/81559220-4f675580-938f-11ea-81d1-53173dd773a4.png)

**Closed by MartaSztuka** 2020-05-11 12:12 UTC
Labels: baked.styles, book:physics, impact:recipe.books, prio:high, type:bug
