### ISSUE TITLE
US History => Latest default module Introduction has a broken image

### ISSUE THREAD

**Issue by m1yag1** [openstax/cnx-recipes#794] opened 2019-01-18 19:02 UTC
# What happened?

During comparison of two webview pages for US History on staging I found there was no image on the introduction of the first module when comparing latest version to an older version. The latest version did not have an image and showed a broken image icon.

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
Yes
- **Does this happen in one place, a few places, or everywhere?**:
This seems to be ok in older versions

# Environment:

- **Book(s)**: US History
- **URL/Server**: https://staging.cnx.org/contents/p7ovuIkl@6.16:gMXC1GEM@7/Introduction
https://staging.cnx.org/contents/p7ovuIkl@7.1:gMXC1GEM@11/Introduction
- **Location (page number, chapter/section)**: default module
- **Suggested nearby searchable text**: 
- **Browser**: Chrome

# Screenshots

![image](https://user-images.githubusercontent.com/8730430/51407031-6e016780-1b20-11e9-98c2-1cc9f718f692.png)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by openstaxalina** [comment] 2019-01-18 21:17
One explanation might be a Batch publish or other content editing test that removed the image.  The image is present on production in version 6.17.

I will request a content refresh to staging, because it is becoming challenging to do content testing on staging now that so many changes have been made via Batch.

**Comment by openstaxalina** [comment] 2019-02-14 23:27
Confirmed this was fixed by latest content refresh to staging; closing: https://staging.cnx.org/contents/p7ovuIkl@8.1:gMXC1GEM@8/Introduction

**Closed by openstaxalina** 2019-02-14 23:27 UTC
