### ISSUE TITLE
OPS-0012 Anthropology Bullet List Not Supported in Web Preview - Preface Section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4202] opened 2021-11-05 12:04 UTC
Bullet list not supported at preface section in Web Preview, but it's supported in PDF view. Please check & resolve.

![PDF](https://user-images.githubusercontent.com/86622862/140507605-122cab20-7d86-47e7-af66-ff2a8cd81192.png)
![POET](https://user-images.githubusercontent.com/86622862/140507609-02de3fa6-ce22-4634-be66-22afb9e43510.png)
![Web-Preview](https://user-images.githubusercontent.com/86622862/140507611-ee96055b-2b7e-4dc2-afb4-ddad3525ce41.png)

# Bug Location(s)
collection ID: col00002
server: https://teal-flea-z00dgejm.ws-us17.gitpod.io/
chapter/section: Preface
surrounding text: In addressing social inequality, the text drives

**Comment by lwtchu** [comment] 2022-01-10 20:28
Propose to fix with baked styles for web

**Comment by lwtchu** [comment] 2023-01-20 17:27
I believe we already fixed this, but please verify. It'll show up in webview when we move this title to adopt baked styles for web.

**Comment by wilkus27** [comment] 2023-01-25 09:47
Checked with code from beefy.bromatology. It's working as intended.

![image](https://user-images.githubusercontent.com/40228854/214531073-2f52cc81-8cfa-45fe-a99d-5897ee23fa1a.png)

**Comment by lwtchu** [comment] 2023-01-25 15:30
@wilkus27 closing thank you

**Closed by lwtchu** 2023-01-25 15:30 UTC
Labels: type:good.first.issue, book:introduction.anthropology, deadline:flex, styles:for.web
