### ISSUE TITLE
Orphaned page numbers in TOC of Bio 2e

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#1719] opened 2019-12-20 16:25 UTC
# Scenario

# Acceptance Criteria (required)

# Steps to Reproduce (required)
* **How many times were you able to reproduce the issue?**
* **Images or Screenshots Included:** [x] Yes  [ ] No  (_attach below_)
<img width="472" alt="Screen Shot 2019-12-20 at 10 23 29 AM" src="https://user-images.githubusercontent.com/1895432/71268639-fe3cc380-2312-11ea-9414-67f22b7e61c8.png">

# Environment: (required)
* **Medium**: [ ] REX [ ] PDF  [ ] cnx.org
* **Instance**: [ ] production  [ ] qa  [ ] staging  [ ] dev  [ ] content
* **OS**: [ ] Mac OSX  [ ] Windows  [ ] iOS  [ ] Android
* **Browser**: [ ] Chrome  [ ] Firefox  [ ] Safari  [ ] Opera  [ ] IE  [ ] Edge

# Impact
* **Severity**: [ ] High [ ] Medium  [ ] Low
* **Frequency of Occurrence**: [ ] High [ ] Medium  [ ] Low

# Next Steps for User
If the card is accepted or rejected, what does user need to know now?

# Test Plan

**Comment by brittweinstein** [comment] 2020-01-07 22:25
This is a duplicate and will be resolved by expanding the margins.

**Comment by openstaxalina** [comment] 2020-01-07 22:26
(for record keeping: duplicate of: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1489)

**Closed by brittweinstein** 2020-01-07 22:25 UTC
Labels: baked.styles, book:biology.2e, type:bug
