### ISSUE TITLE
Symmetry Feedback: Standardize folios - in or not-in the margin?

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1950] opened 2020-02-24 19:22 UTC
# Scenario

I know the EOC folios needed to accommodate the ribbon which is why they're in line with the text.  But do we want this discrepancy or would it be better to standardize?

![2020-02-24_13-19-45](https://user-images.githubusercontent.com/7863733/75183686-a783a980-5708-11ea-954b-3069ec2f4145.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment] 2020-02-25 20:17
This was intended. 

@andymuddimer do you have any strong feelings?

**Comment by lwtchu** [comment] 2020-02-25 20:22
@andymuddimer has no feelings. and he said the words "coolio" to me so we're closing this issue

**Closed by lwtchu** 2020-02-25 20:22 UTC
Labels: baked.styles, book:biology.2e
