### ISSUE TITLE
CLEAN UP: chapters

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#2170] opened 2020-04-07 16:07 UTC
- [x] Remove the shapes from the components
- [x] Remove the page from the shape
- [x] Move the title to the titles component 
- [x] assess if we need a shape for chapters at all

**Comment by ajluk** [comment] 2020-05-14 12:17
Information for testing purposes about font-family in Modules and Chapters (form Larissa):

H2-H5 titles should be all set to Muli except H1 which should be IBM plex sans

**Comment by MartaSztuka** [comment] 2020-05-14 15:56
Word `chapter` lack of style is caused by regression, will be fixed.
![Screenshot from 2020-05-14 15-05-52](https://user-images.githubusercontent.com/47241114/81937864-72467380-95f4-11ea-9c9e-26496c121653.png)

**HS Physics**
![Screenshot from 2020-05-14 13-52-53](https://user-images.githubusercontent.com/47241114/81934540-699f6e80-95ef-11ea-8b79-916a93ade070.png)
**Chemistry 2e** ![Screenshot from 2020-05-14 14-49-49](https://user-images.githubusercontent.com/47241114/81936231-390d0400-95f2-11ea-9272-f01479e4f94b.png) 
**Chemistry AF**
![Screenshot from 2020-05-14 15-02-58](https://user-images.githubusercontent.com/47241114/81937535-08c66500-95f4-11ea-9830-c7c2c7fd3d37.png)
**Anatomy**
![Screenshot from 2020-05-14 15-17-21](https://user-images.githubusercontent.com/47241114/81939003-0bc25500-95f6-11ea-9af3-9f3c0d5c9f47.png)
**Biology 2e**
![Screenshot from 2020-05-14 15-43-52](https://user-images.githubusercontent.com/47241114/81941922-bee07d80-95f9-11ea-8bc5-6ecf00234af9.png)
**AP Biology**
![Screenshot from 2020-05-14 15-57-41](https://user-images.githubusercontent.com/47241114/81943436-abcead00-95fb-11ea-96b4-7272d6c2f1fa.png)
**Concepts of Biology**
![Screenshot from 2020-05-14 15-59-42](https://user-images.githubusercontent.com/47241114/81943893-3fa07900-95fc-11ea-8229-d1bb302e40bc.png)
**Microbiology**
![Screenshot from 2020-05-14 16-40-55](https://user-images.githubusercontent.com/47241114/81948363-f05d4700-9601-11ea-82e0-3b5dfdd29521.png)
**College Physics**
![Screenshot from 2020-05-14 17-44-31](https://user-images.githubusercontent.com/47241114/81955820-dffd9a00-960a-11ea-8b59-9b1872d3cb89.png)
**University Physics**
![Screenshot from 2020-05-14 17-53-19](https://user-images.githubusercontent.com/47241114/81956691-e5a7af80-960b-11ea-8ba5-0a10458090db.png)

**Closed by MartaSztuka** 2020-05-14 15:56 UTC
Labels: baked.styles
