### ISSUE TITLE
Difference in numbering in answer key

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#855] opened 2019-02-18 13:21 UTC
Answer key in PDF goes like this:
1. Try it answers (chapter 1 - chapter 9)
2. Odd answers (Review exercise & Practice test for #1)
                          (Review exercise & Practice test for #2)
                          (Review exercise & Practice test for #3) etc.

In webview*:
CHAPTER 1: 1. Try it (1.1, 1.2, 1.3 (...) 1.60)
                      2.  Section 1.1 Exercise (1,3,5...67) ----odd numbers
                      3.  Section 1.2 Exercise (69, 71, 73...127) ...and so it goes to Subsection 1.6
                      4.  Review Exercise (374...442) -----even numbers
                      5.  Practice test (444...472)
                                                                                                                  it's within one chapter*

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:Gn5_arhA@8.1/Chapter-1

It's part of bigger problem with numbering system both in webview and PDF, I think this needs to by unify in all math books.

**Comment by openstaxalina** [comment] 2019-02-18 14:59
The webview Answer Key should contain the same answers that the PDF Answer Key contains.  Unfortunately it is out of scope for Assignable Webview to make adjustments to the PDF Answer Keys.

If we cannot match the webview Answer Key to the PDF Answer Key, we will need to suppress the Answer Key in webview and create a separate Student Solution Guide/Manual on openstax.org.

**Comment by Adrianltd** [comment] 2019-02-21 13:04
Duplicate of https://github.com/openstax/cnx-recipes/issues/857

**Closed** 2019-02-22 13:01 UTC
Labels: book:college.algebra, prio:high
