### ISSUE TITLE
Two columns in three columns layout

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#2486] opened 2020-07-09 13:22 UTC
In exercises modules (Section Exercises, EOC Exercises, Answer Key) with three columns layout sometimes appear only two columns:

![image](https://user-images.githubusercontent.com/40228854/87045146-d4d47e00-c1f7-11ea-93b7-c390f33721e0.png)

Screenshot is from **Prealgebra 2e**

**Comment by brittweinstein** [comment] 2020-07-09 14:12
This occurs in two spots. @lwtchu could you please assign priority to this?

**Comment by brittweinstein** [comment] 2020-07-09 14:23
Another thought that Alan had is maybe this could be something wonky within the content since it is so limited?

**Comment by lwtchu** [comment] 2020-07-09 14:48
![Screen Shot 2020-07-09 at 9 47 30 AM](https://user-images.githubusercontent.com/11299125/87054862-3af5dc80-c1c9-11ea-8739-4768821d2a50.png)
In the past the lists have been able to slim down to fix - is this a limitation with the new pipeline? or new designs?

**Comment by lwtchu** [comment] 2020-07-10 16:20
Update: Talked to BrittanyJ. She'll take a look. Might be something in the code

**Comment by MartaSztuka** [comment] 2020-08-07 15:21
@lwtchu Two columns in Answer Key occurs in other books too.
 
### Calcusus
![Screenshot from 2020-08-07 17-15-51](https://user-images.githubusercontent.com/47241114/89660468-aa96de80-d8d1-11ea-9b28-45b608cfb828.png)
### Precalculus
![Screenshot from 2020-08-07 17-17-07](https://user-images.githubusercontent.com/47241114/89660593-d87c2300-d8d1-11ea-941b-951a0d121c9e.png)
### College Algebra coreq
![Screenshot from 2020-08-07 17-17-39](https://user-images.githubusercontent.com/47241114/89660649-ec278980-d8d1-11ea-877a-5bccf599b4b8.png)

**Comment by lwtchu** [comment] 2020-08-07 15:52
is this because of spacing issues? I'm not sure how far you got with the investigation on this @brittany-johnson :eyes:

**Comment by brittany-johnson** [comment] 2020-08-07 15:55
Haven't looked at this in a few weeks ☠️
Once the fractions issue is resolved I can take a look again - hopefully sometime next week

**Comment by lwtchu** [comment] 2020-08-07 16:46
@brittany-johnson okay not super high priority - not a show stopper at this point for the coreqs

**Comment by ajluk** [comment] 2020-09-22 15:52
@lwtchu in Prealgebra 2e lists are placed next to the exercise number as they should be now. The new line has been removed from there in the content: 
![image](https://user-images.githubusercontent.com/55203598/93906125-1b684d80-fcfc-11ea-837b-d36d4c0b5b20.png)
But as you can see these exercises are still displaying in two columns intsead of three. Natalia is working on the same problem in EoC and section exercises in this PR: #2761

**Comment by ajluk** [comment] 2020-09-22 16:01
In Precalculus the problem still occurs: 
![image](https://user-images.githubusercontent.com/55203598/93907408-95e59d00-fcfd-11ea-859b-1a0720179507.png)
I'm wondering if this can be caused by the `;` and `whitespace` placed inside the math element and therefore the it can't break properly there. But I'm not sure here: 
![image](https://user-images.githubusercontent.com/55203598/93907214-5a4ad300-fcfd-11ea-9b88-1c91e9450468.png)

**Comment by lwtchu** [comment] 2020-09-22 16:38
@ajluk it could be possible. i just removed the math white text and replaced with just a regular non-math space. do you mind regenerating to see?

**Comment by ajluk** [comment] 2020-09-23 07:08
Sure! No problem, I will check it today and I will also check other the places mentioned in the issue in the rest of the books (I needed to fetch content yesterday).

**Comment by ajluk** [comment] 2020-09-23 08:14
@lwtchu the content change you made in Precalculus worked and it looks good now: 
![image](https://user-images.githubusercontent.com/55203598/93985462-65e1dc80-fd85-11ea-86ec-ab5f1164ff38.png)

**Comment by ajluk** [comment] 2020-09-23 08:25
In Calculus the first issue is caused by unbreakable long math equation: 
![image](https://user-images.githubusercontent.com/55203598/93986715-f836b000-fd86-11ea-94be-8186454994ee.png). So I guess we can't do much about it in the code.

**Comment by ajluk** [comment] 2020-09-23 11:33
In College Algebra Coreq I have tried to decrease paddings in table cells (td, th) from 0.7rem to 0.4 rem and this is how it looks now: 
![image](https://user-images.githubusercontent.com/55203598/94006054-8a4ab280-fd9f-11ea-89a3-0d30e03b71f7.png), but as you can see the table in the 8 solution is moved and the solution from the above can't jump up there into the third column, but I guess here the cause is the inline list in the 7 solution on which Natalia is working. @lwtchu  you want me to implement to this decreased padding for the tables in the Answer Key in College Algebra Coreq (it's using separate shape so other books won't be affected by this)?

**Comment by lwtchu** [comment] 2020-09-23 14:22
@ajluk i think we can hit them all - we still need to do some content changes for the other titles. i would suggest marta can just look at elementary algebra (for the dev math), statistics (for stats trio), calculus vol 2 (for calc), and the coreq will cover the entire precal series. 

as for the long equation in calculus - i think we can do something to fix it on the content side.

**Comment by ajluk** [comment] 2020-09-23 14:33
@lwtchu Thank you!

**Comment by ajluk** [comment] 2020-09-25 17:25
@MartaSztuka >> Information for testing purposes: 
Circled lists should be testes in EOS and EOC exercises columns and Answer Key solutions columns in one book from every series: dev-math (f.ex. Prealgebra 2e, Elementary Algebra...), precalculus-coreq (College Algebra Coreq), calculus (Calculus vol 1 or 2 or 3).  @lwtchu do you thin it will be enough?

**Comment by lwtchu** [comment] 2020-10-05 13:57
@ajluk let's do elementary algebra, college algebra coreq, calculus vol 2

**Comment by brittweinstein** [comment] 2020-10-13 13:55
@ajluk please see Larissa's note above.

**Comment by MartaSztuka** [comment] 2020-10-20 12:17
## Failed
### College Algebra coreq
@ajluk Heres are location where 2 column exercises still occur.
#### EoC Exercises
1.![Screenshot from 2020-10-20 10-11-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/519e3983-663b-4c01-b163-d33a1c538672)
2.![Screenshot from 2020-10-20 10-13-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0ed40449-6def-418f-b374-cce600990fbb)
3.![Screenshot from 2020-10-20 10-53-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/13ee3a66-e45a-469a-b0f2-768730c5c076)
4.![Screenshot from 2020-10-20 11-00-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5ceee4f1-d03a-4eac-8196-7663fc69835b)
5.![Screenshot from 2020-10-20 13-43-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/0c5e06bb-d606-4f39-9ea9-3ea386ecdd9d)
6. ![Screenshot from 2020-10-20 14-08-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/72c251aa-2955-492a-b1de-f1b14bf110cb)
7. ![Screenshot from 2020-10-20 14-09-52.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9a117c76-bfb5-44f1-b0e0-ea05c41aa22f)
8. ![Screenshot from 2020-10-20 14-14-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f6e9ba31-c6bc-447a-8f83-7a5fb019f1fd)

**Comment by MartaSztuka** [comment] 2020-10-20 13:20
## Failed
### College Algebra coreq
#### Answer Key
1.![Screenshot from 2020-10-20 14-17-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/23c35eec-585a-49eb-9de8-e32047841be8)
2.![Screenshot from 2020-10-20 14-20-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3bcb05a1-f459-4d7c-bdbc-f2c3e1b4c4fc)
3.![Screenshot from 2020-10-20 14-20-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/45e58ea3-11a7-42f2-bf02-7a001d0f009a)
4.![Screenshot from 2020-10-20 14-21-23.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d2a74f4a-6682-45b5-8bba-a01fc08441e5)
5.![Screenshot from 2020-10-20 14-22-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/f86a2cd5-0631-47a5-96e9-577c5ed3342e)
6.![Screenshot from 2020-10-20 14-30-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/45b8d163-2cb6-4309-b15c-d826f3fc6c2a)
7.![Screenshot from 2020-10-20 14-31-20.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9f416c2d-5627-43c8-b5bf-e68c0a98b187)
8.![Screenshot from 2020-10-20 14-33-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4159aef0-a0c5-40a8-800b-b7fc1a08169f)

**Comment by lwtchu** [comment] 2020-10-20 13:58
Looking at these, I think it might be mostly a long math problem. In the 8th example, I believe these have the `material-set-2` classes on them :eyes:?

**Comment by MartaSztuka** [comment] 2020-10-21 08:35
## PASSED
### College Algebra coreq
#### Section Exercises ![Screenshot from 2020-10-21 08-56-53](https://user-images.githubusercontent.com/47241114/96694229-7be4bc00-1388-11eb-9871-5861d0b24f88.png)
2. Examples 
![Screenshot from 2020-10-21 10-33-49](https://user-images.githubusercontent.com/47241114/96694666-07f6e380-1389-11eb-82cf-68a8113c181b.png)
3. Practice makes perfect
![Screenshot from 2020-10-21 10-33-02](https://user-images.githubusercontent.com/47241114/96694673-09281080-1389-11eb-9e85-717be5d7beb2.png)

**Comment by MartaSztuka** [comment] 2020-10-21 13:28
## FAILED
### Elementary Algebra
### End of Chapter Exercises
#### 1. Everyday Math, header is unstyled![Screenshot from 2020-10-21 15-22-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a7a93507-4a1b-4dda-8349-116677310657)
#### 2. No space between token and number 5 in Practice Test![Screenshot from 2020-10-21 15-23-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cdf6c8ff-cd6b-4224-b00a-3f7a262e6b73)

**Comment by MartaSztuka** [comment] 2020-10-21 13:39
## PASSED
### Elementary Algebra
#### Answer Key![Screenshot from 2020-10-21 15-29-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ca6a5056-6e75-47d8-9fd4-6b173ca14f72)
#### Section Exercises ![Screenshot from 2020-10-21 15-35-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a0e13c9f-149c-40db-9137-ba1c3745c803)
#### Try it![Screenshot from 2020-10-21 15-37-15.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/82bb60a9-24d6-42f6-8c9a-dc1cf54f5132)
#### Examples![Screenshot from 2020-10-21 15-37-42.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d2f44a89-fc6a-4d8e-ab7c-344bf2bfab94)

**Comment by MartaSztuka** [comment] 2020-10-21 13:49
## FAILED
### Calculus 2
#### Answer Key
1. ![Screenshot from 2020-10-21 15-43-53.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7e261c46-e396-4ded-bc95-a90252b28b5c)
2. ![Screenshot from 2020-10-21 15-44-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e1b3a3f1-7e88-48ef-8bc7-9e3bc661b5df)
3. ![Screenshot from 2020-10-21 15-45-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66f843e9-8d53-4c4b-9d15-a25e188aa83b)
4. ![Screenshot from 2020-10-21 15-46-37.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7bd8947b-8744-4e07-8402-0e5d8059b115)
5. ![Screenshot from 2020-10-21 15-47-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b39d586f-3149-40a9-96a5-e1727b0b2440)
6. ![Screenshot from 2020-10-21 15-48-04.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d302b3eb-5d72-45b8-ad16-1200c7057774)
7. ![Screenshot from 2020-10-21 15-48-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/b7be7b73-0730-495d-b6a9-3a43f7d9cfc2)

**Comment by MartaSztuka** [comment] 2020-10-21 13:57
## PASSED
### Calculus 2
#### End of Chapter Exercises![Screenshot from 2020-10-21 15-51-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/5c399d77-a1ed-4648-88d0-96981a9c839d)

**Comment by MartaSztuka** [comment] 2020-10-21 14:09
## FAILED
### Calculus 2
#### End of Section Exercises
1. ![Screenshot from 2020-10-21 15-56-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/78a0fa41-b704-458d-ac55-ba0d54e6dd38)
2. ![Screenshot from 2020-10-21 15-58-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fd130c5e-ac57-47ae-b5d0-033199d4f497)
3. ![Screenshot from 2020-10-21 15-58-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cda678f2-8d7e-437b-97bd-14235ffa7248)
4. ![Screenshot from 2020-10-21 15-59-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/7d4c7ec6-432a-488b-8c66-406ed1354a99)
5. ![Screenshot from 2020-10-21 15-59-54.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24896f00-7abb-4220-99c6-349ee217991f)
6. ![Screenshot from 2020-10-21 16-00-33.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e02c7a5-cf79-4c44-959d-8818149b05d8)
7. ![Screenshot from 2020-10-21 16-00-58.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4602909b-61b8-4ae6-a967-f46e3cdc73d2)
8. ![Screenshot from 2020-10-21 16-01-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/24764644-af39-400b-ba04-ed3c98bd3ee2)
9. ![Screenshot from 2020-10-21 16-02-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4570e69b-df55-4e02-83cd-f39bb518cf09)
10. @ajluk There should be tokens not ABCs ![Screenshot from 2020-10-21 16-03-48.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3735ca09-2f39-426c-b1e3-178fbfdf473e)![Screenshot from 2020-10-21 16-04-57.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8562172-4c86-4db7-a7ae-319deead3751)
11. ![Screenshot from 2020-10-21 16-05-36.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c8dc4556-e337-4412-b0c9-97540ab4f1ce)
12. ![Screenshot from 2020-10-21 16-06-19.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e40873e-af72-4711-a954-235034061404)
13. ![Screenshot from 2020-10-21 16-07-08.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/78aba6d8-c723-4fc9-b97f-349d82ea4c07)
14. ![Screenshot from 2020-10-21 16-07-40.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/c3156f47-b1dc-482b-9233-9163b9f5c0fd)

**Comment by MartaSztuka** [comment] 2020-10-21 14:10
## FAILED
### Calculus 2
#### Example token lists![Screenshot from 2020-10-21 16-08-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/069b2d52-7752-46d0-a79f-5e42b3ffc02e)

**Comment by ajluk** [comment] 2020-10-22 16:01
@lwtchu @MartaSztuka In screenshots from **College Algebra Coreq** EoC Exercises in points **1, 3, 4, 7, 8** the exercises have class `material-set-2`, so they should be in two columns: 

![image](https://user-images.githubusercontent.com/55203598/96897241-b0db3680-148e-11eb-9ce6-b9f385af5602.png)
![image](https://user-images.githubusercontent.com/55203598/96897639-18918180-148f-11eb-8f2d-e28bbbb46b83.png)
![image](https://user-images.githubusercontent.com/55203598/96898466-06fca980-1490-11eb-8b9f-98532b1195e6.png)
![image](https://user-images.githubusercontent.com/55203598/96898579-2a275900-1490-11eb-8426-0e450dbd16cc.png)
The rest is problem with math breaking.

**Comment by lwtchu** [comment] 2020-10-22 16:34
@ajluk yep these will be content changes  - if it's alright with you @MartaSztuka , it should be ok to pass from a code stand point.

**Comment by ajluk** [comment] 2020-10-22 16:37
@lwtchu do you have in mind all of the three books? Or should I also check them out?

**Comment by lwtchu** [comment] 2020-10-22 16:40
@ajluk if there's locations where there aren't a lot of math, and they display correctly, we should pass it :eyes: and it looks like most of the issues marta opened were due to long math. 

the token list being missing is also accurate as they were not created with the tokens initially.

**Comment by ajluk** [comment] 2020-10-22 16:51
@lwtchu I have one location which concerns me in Elementary Algebra (EoC point 2 ):
![image](https://user-images.githubusercontent.com/55203598/96904464-73c77200-1497-11eb-8c00-23ee0f747aad.png)
and it occurred these are paragraphs, not tokens lists: 
![image](https://user-images.githubusercontent.com/55203598/96904376-51cdef80-1497-11eb-8935-3315c29cd3e6.png)
I guess there also some white space needed after math?

**Comment by lwtchu** [comment] 2020-10-22 17:01
ah okay can you give me the location for that h5  

the other para stuff i'm not as concerned we can clean up some of that in the content

**Comment by ajluk** [comment] 2020-10-22 17:03
Here is the H5 title location: ![image](https://user-images.githubusercontent.com/55203598/96905733-251ad780-1499-11eb-8fb4-46bbc0996fd1.png)

**Comment by lwtchu** [comment] 2020-10-22 18:09
I opened a card for the H5. I'll close this card :eyes: feel free to reopen if you have any more concerns !

**Closed by lwtchu** 2020-10-22 18:09 UTC
Labels: book:calculus, book:calculus.2, book:calculus.3, book:collegealgebra.coreq, book:prealgebra.2e, book:precalculus, theme:corn
