### ISSUE TITLE
CARNIVAL CLEAN UP - review shapes for EOC and reduce clutter if possible

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#1767] opened 2020-01-16 14:15 UTC
There are many shapes that seem to be repeating the same structure for the different EOC parts, do we need all of them or can we consolidate them to avoid future bugs.

**Comment by wilkus27** [comment] 2020-05-05 09:24
Duplicate of https://github.com/openstax/cnx-recipes/issues/1942. I'm closing this issue.

**Closed by wilkus27** 2020-05-05 09:24 UTC
Labels: baked.styles.improve.framework
