### ISSUE TITLE
Footnote numbering inconsistency

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#634] opened 2018-09-17 19:36 UTC
# Scenario

Footnotes in Introductory Business Statistics are numbered continuously across modules in webview, but they restart at 1 in every module in the pdf. Example:
https://staging.cnx.org/contents/tWu56V64@36.1:3UZ5oaPG@8/1-4-Experimental-Design-and-Ethics

# Reproducibility Details

- **Impact area**: staging and presumably production
- **User**: all
- **URL / Location**: https://staging.cnx.org/contents/tWu56V64@36.1:3UZ5oaPG@8/1-4-Experimental-Design-and-Ethics
- **How many times were you able to reproduce the issue?** every footnote per chapter

## Screenshots

<img width="1328" alt="screen shot 2018-09-17 at 2 33 05 pm" src="https://user-images.githubusercontent.com/1895432/45645678-d531e100-ba86-11e8-8728-68210cf49c48.png">

# Environment:

- **Instance**: staging
- **OS**: 10.13.6
- **Browser**: firefox

# Impact

- **Severity**: unsure. Larissa says to tell y'all we're sorry
- **Frequency of occurrence**: all cross-module footnotes

**Comment by openstaxalina** [comment] 2018-09-17 21:33
*Decision:* some of the content involved in this change is "in flight" as part of https://github.com/Connexions/content-managers/issues/313.  

Also, we have an open issue for footnote improvements: https://github.com/Connexions/cnx-recipes/issues/566

Therefore, we will wait for these two issues to complete, then retest to determine if this issue is resolved.

**Comment by openstaxalina** [comment] 2018-11-05 22:39
The specific issue in this screenshot was resolved by making the content a parenthetical reference rather than a footnote.

@oscryan would you be willing to re-test more cases and let us know if this is resolved?  If this is still an issue, please provide more examples for testing.  Thank you!  cc @lwtchu

**Comment by oscryan** [comment] 2018-11-06 16:33
Not resolved: https://staging.cnx.org/contents/tWu56V64@39.1:PhCRzjQp@18/1-2-Data-Sampling-and-Variation-in-Data-and-Sampling
<img width="1400" alt="screen shot 2018-11-06 at 10 32 38 am" src="https://user-images.githubusercontent.com/1895432/48078577-5f591480-e1af-11e8-878d-5580e64bc72c.png">

**Comment by openstaxalina** [comment] 2018-11-08 19:32
We will handle this after the linebreaks transforms issue.
Impact: footnotes in unbaked books will appear inline in the content instead of at the bottom of the page.

**Comment by openstaxalina** [comment] 2019-03-12 17:44
duplicate of #566; closing.

**Closed by openstaxalina** 2019-03-12 17:44 UTC
Labels: book:introductory.business.statistics
