### ISSUE TITLE
Replace Figure with LO

### ISSUE THREAD

**Issue by tomjw64** [openstax/cnx-recipes#791] opened 2019-01-18 17:18 UTC
Probably should be in webview repo, but found during doomsday testing
https://staging.cnx.org/contents/kg0cimBs@2.1:yGN5G-zz@2.1/Questions
![screenshot_13](https://user-images.githubusercontent.com/1285308/51402257-984c2880-1b12-11e9-9828-8f921a9f8ebf.png)

**Comment by helenemccarron** [comment] 2019-01-18 18:35
There is also the issue of the figure numbering

**Comment by openstaxalina** [comment] 2019-01-22 17:09
Will be resolved with https://app.zenhub.com/workspaces/cnx-team-5af1f4cc12da5e6d74331b60/issues/openstax/webview/2160; closing.

**Comment by Stackblocks** [comment] 2019-02-01 19:04
Test collection on devb did not have LOs (also devb was dying) but Helene ran the recipe against the draft content and the Figure -> LO fix was in place. Will be re-testing on Staging with updated content.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/09fced01-bb6b-4785-8713-00a87ef910e0)

**Comment by openstaxalina** [comment] 2019-02-01 19:45
@brittany-johnson is there any possibility of having a space after "LO #.#"?  Right now it's running right up to the text, making it a little difficult to parse/read.

**Comment by helenemccarron** [comment] 2019-02-01 19:48
This is an unstyled, ad-hoc testing screenshot to show that the functionality is working since the content is missing on devb. We will need to test it on staging, where it will look as it should (🤞 )

**Comment by Stackblocks** [comment] 2019-02-04 20:42
Displaying as specified with updated version of content / code.

![image.png](https://images.zenhubusercontent.com/5af1f4c24b5806bc2bd257f2/6bed7d32-2944-4677-b837-ea9fb3b4728b)

**Closed by Stackblocks** 2019-02-04 20:42 UTC
Labels: book:accounting, type:doomsday

**Comment by openstaxalina** [comment] 2019-02-12 17:19
confirmed fixed in final Managerial Accounting webview:
<img width="1182" alt="screen shot 2019-02-12 at 11 17 01 am" src="https://user-images.githubusercontent.com/7863733/52654669-1c968f00-2eb8-11e9-93ec-93b32bb6964f.png">
