### ISSUE TITLE
Incorrect caption of Figures

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#852] opened 2019-02-15 16:09 UTC
In PDF figure's caption in Chapter 2 goes like this:

**example:**
Chapter 2
Introduction (Figure 1)
Chapter 2.1 ( 'Figure 1' to 'Figure 12')
Chapter 2.2 ('Figure 1' to 'Figure 24') etc.

![aa pdf](https://user-images.githubusercontent.com/47241114/52868516-e0775e80-3143-11e9-9d2d-c137212d1504.png)

In webview  figure's caption in Chapter 2 goes like this:
Chapter 2
Introduction (Figure 2.1)
Chapters 2.1 - 2.4 (Figure 2.2 - Figure 2.54) etc.

![aa](https://user-images.githubusercontent.com/47241114/52868564-fe44c380-3143-11e9-8299-b49303640326.png)

Within each chapter there are subsections captioned 1.1, 1.2, 1.3 etc. and this is misleading.

https://katalyst01.cnx.org/contents/_VPq4foj@8.1:VYbyR_vl@10/2-4-Fitting-Linear-Models-to-Data

Please, change Figure 2.2 system in Figure 2 (as in PDF) and start it from 'Figure 1' in every subsection.
Thanks!

**Comment by Adrianltd** [comment] 2019-02-21 10:34
Duplicate of https://github.com/openstax/cnx-recipes/issues/848

**Comment by MartaSztuka** [comment] 2019-02-22 12:51
It's fixed, looks just like PDF

**Closed** 2019-02-22 12:51 UTC
Labels: book:precalculus, prio:high
