### ISSUE TITLE
Check your understanding number

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#2237] opened 2020-04-16 09:38 UTC
There's an extra space between header and number
![Screenshot from 2020-04-16 11-36-51](https://user-images.githubusercontent.com/47241114/79440756-a9fed300-7fd6-11ea-9d8e-4845e4213645.png)

**Comment by wilkus27** [comment] 2020-04-16 10:04
Duplicate of https://github.com/openstax/cnx-recipes/issues/2213. Close the issue.

**Closed by wilkus27** 2020-04-16 10:04 UTC
Labels: baked.styles, book:fizyka
