### ISSUE TITLE
[Carnival] Support Nested EOC Elements in the ToC

### ISSUE THREAD

**Issue by yblock** [openstax/cnx-recipes#1692] opened 2019-12-11 19:16 UTC
# What happened?

Specific to microbiology: If EoC content being displayed is intended, they should not be in a numbered list.

# Reproducibility Details

- **Does it also happen in an incognito window?**: 
- **Does this happen in one place, a few places, or everywhere?**:

# Environment:

- **Book(s)**: Microbio, A&P
- **URL/Server**: 
- **Location (page number, chapter/section)**: ToC in PDF
- **Suggested nearby searchable text**: 
- **Browser**:

# Screenshots

![ToC](https://user-images.githubusercontent.com/7863733/70922538-e4863e00-1feb-11ea-88a8-7a4b5f904142.jpeg)

# Additional notes

 (_For example, steps to reproduce, related issues, more context, etc._)

**Comment by brittweinstein** [comment] 2019-12-13 19:36
Assigning to @openstaxalina for prio

**Comment by brittweinstein** [comment] 2019-12-16 16:05
Probably related to https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1653

**Comment by brittweinstein** [comment] 2019-12-16 16:05
@annaludwin could you please enable this for all books that contain this? This would include Microbiology.

**Comment by annaludwin** [comment] 2019-12-16 17:17
@brittweinstein  Hi, I'm not sure this task is for me, becouse I'm not in this project :)

**Comment by ajluk** [comment] 2019-12-17 08:19
@brittweinstein I think was about me. I will enable the flag to use the mixin that support nested ToC in Microbiology as well.

**Comment by lwtchu** [comment] 2019-12-20 15:43
Referring back to #1070, the EOC sections are not supposed to be in the table of contents. Is it possible to remove them.

**Comment by brittany-johnson** [comment] 2020-01-06 20:32
This PR from @ajluk enables a release flag that removes the numbering. 
https://github.com/openstax/cnx-recipes/pull/1708

So instead the EOC sections should be completely removed from the TOC? 

Want to make sure since it's after the holiday. Thanks!

**Comment by lwtchu** [comment] 2020-01-08 21:52
After discussing with Alina and Anthony, let's keep the EOC content, but have it styled like the rest of the modules/introduction.

However, let's REMOVE the nested content (multiple choice, fill in the blank, short answer, critical thinking). 

Let me know if that makes any sense. Or no sense.

**Comment by ajluk** [comment] 2020-01-09 08:55
Please let me know when this design change will be confirmed.

**Comment by lwtchu** [comment] 2020-01-09 16:06
![Screen Shot 2020-01-09 at 10 06 15 AM](https://user-images.githubusercontent.com/11299125/72083599-b41e8080-32c7-11ea-9a4f-c59d6af6e358.png)
Here's the mock up

**Comment by brittany-johnson** [comment] 2020-01-14 14:45
The change in the related PR effect all books in the carnival theme so I'm adding a new label to this issue.

**Comment by ajluk** [comment] 2020-01-17 16:34
Changes in Theme Design Specs:
_**Component**_ TocEocCompositeChapterList
    removed properties:
      list-style: none,
      padding-left: h-grid(2),
      margin-left: 0,
      display: block
    properties: 
      display: none,

**Comment by lwtchu** [comment] 2020-01-21 22:13
@ajluk updated. thank you

**Comment by MartaSztuka** [comment] 2020-01-22 10:15
Microbiology:
![Screenshot from 2020-01-22 11-13-53](https://user-images.githubusercontent.com/47241114/72885504-5d259c00-3d08-11ea-8d57-d9d987f85fcf.png)
APBiology:
![Screenshot from 2020-01-22 11-07-47](https://user-images.githubusercontent.com/47241114/72885565-76c6e380-3d08-11ea-9e0f-83d9fdf6b9ec.png)

**Closed by MartaSztuka** 2020-01-22 10:15 UTC
Labels: baked.styles, book:microbiology
