### ISSUE TITLE
carnival theme: reduce figure number, caption size

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#1992] opened 2020-03-02 17:49 UTC
For space saving reasons:

Let's reduce the figure caption throughout the book to be `font-scale(-1)` 

This applies to ALL figure numbers and captions.

**Comment by helenemccarron** [comment] 2020-03-04 16:48
This looks like a duplicate of #1992

**Comment by MartaSztuka** [comment] 2020-03-25 09:16
**College Physics**
![Screenshot from 2020-03-25 09-46-06](https://user-images.githubusercontent.com/47241114/77520318-5854a400-6e81-11ea-9f2f-b27fde36b3b6.png)
**HS Physics**
![Screenshot from 2020-03-25 09-47-44](https://user-images.githubusercontent.com/47241114/77520433-7fab7100-6e81-11ea-8456-d2989fee3171.png)
**Biology 2e**
![Screenshot from 2020-03-25 10-15-35](https://user-images.githubusercontent.com/47241114/77520517-9c47a900-6e81-11ea-902f-f954c3912b23.png)

**Closed by MartaSztuka** 2020-03-25 09:16 UTC
