### ISSUE TITLE
Symmetry Feedback: First Two Pages of Chapter Opener Have Smaller Width

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#2017] opened 2020-03-05 16:40 UTC
# Scenario

![Screen Shot 2020-03-05 at 10 40 38 AM](https://user-images.githubusercontent.com/7863733/76003511-c551cb00-5ecd-11ea-9f88-6fadc3095999.png)

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment] 2020-03-06 21:06
This needs to be adjusted to full width for the second page. I think it might be encompassed by some other change, but I'm not sure?

**Comment by wilkus27** [comment] 2020-03-09 08:31
@lwtchu This is caused by new way of displaying elements from Introduction page. I added comment that this effect appears and you said that it is ok: https://github.com/openstax/cnx-recipes/issues/1627#issuecomment-586353699 

Generally, problem occurs because page on which we can find Chapter Outline box has to be 2in thinner. We can't predict when introduction text with Chapter Outline box jump to the second page, so all second pages has to have smaller width.

**Comment by lwtchu** [comment] 2020-03-09 14:07
@wilkus27 ah i thought this was applicable if the chapter outline would go thru to the second page. i'll close this issue.

**Closed by lwtchu** 2020-03-09 14:07 UTC
Labels: baked.styles, book:physics
