### ISSUE TITLE
Implement Key Concepts

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2361] opened 2020-05-27 17:36 UTC
Documentation: https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/2322 

Books: 
- [ ] Prealgebra 2e 
- [ ] Elem Alg 2e 
- [ ] Int Alg 2e

**Comment by wilkus27** [comment] 2020-07-07 12:15
Duplicate of https://github.com/openstax/cnx-recipes/issues/2357

**Closed by wilkus27** 2020-07-07 12:15 UTC
Labels: book:elementary.algebra.2e, book:intermediate.algebra.2e, book:prealgebra.2e, theme:corn
