### ISSUE TITLE
OPS-0012 Composition_Interactive opening issue in webview

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4072] opened 2021-08-25 13:09 UTC
Files in the interactive link could not be opened in the web view. Kindly check and resolve this issue.

CNXML:
![interactive_cnxml](https://user-images.githubusercontent.com/86622862/130795905-17d7362b-015a-42c0-992f-a9a3cf596f22.png)

Webview:
![interactive](https://user-images.githubusercontent.com/86622862/130795960-2995b935-c733-4343-867e-aba9a1d0d7df.png)

# Bug Location(s)
collection ID: col00001
server: https://copper-anteater-egyq5vxq.ws-us16.gitpod.io/
chapter/section: chapter 18/18.5
surrounding text: As preparation for writing, consider different types of media,

**Comment by lwtchu** [comment] 2021-08-25 14:43
This is a duplicate of https://github.com/openstax/cnx/issues/1644. @ne-newton's team is working to resolve the hosting issue. We can leave this issue open to keep track or ask for updates.

**Comment by srm-openstax** [comment] 2021-08-25 16:55
We are unable to access ticket # 1644. That's why we raised a new ticket.

**Comment by lwtchu** [comment] 2023-01-23 19:16
New year cleaning: Other teams are doing work to resolve this. Closing on our end.

**Closed by lwtchu** 2023-01-23 19:16 UTC
Labels: book:english.comp.writing.guide, status:moved.repo, status:disco.webview
