### ISSUE TITLE
AmGov 3e: Table styling missing 

### ISSUE THREAD

**Issue by mwest-WWprod** [openstax/cnx-recipes#3944] opened 2021-06-22 22:19 UTC
GLOBAL 
Example given from AmGov 3e Chapter 15 Module 3
content02 - m10260 - Col10116

![Table Spacing](https://user-images.githubusercontent.com/19212926/122995208-4ceb7380-d377-11eb-9694-0a0b0bf846f6.PNG)

Table spacing between columns is tight and sometimes the text comes close to overlapping in adjacent columns. For best user experience we will need to add spacing or table rules. If this can be done easily via a class change or other type of markup change (e.g. changing column widths) let us know and we'll implement accordingly.

### Comment from Larissa
Can we make sure table, table title, table, numbering and caption styling are present?
Reference cards: #3185 #3183

**Comment by openstaxalina** [comment] 2021-06-22 22:22
@lwtchu here is the issue we discussed - would be top priority if we are making a change. AmGov 3e PDF needs to be generated before July 28 (pub date). cc @anthonypalmiotto in case you wanted to review this request

**Comment by lwtchu** [comment] 2021-06-23 16:58
@mwest-WWprod 😓 do you mind checking the module number? i can't find the table here https://legacy-content02.cnx.org/content/m10183/latest/

**Comment by mwest-WWprod** [comment] 2021-06-23 19:16
My mistake! I had two chapters opened and I pulled the wrong ID, this table is in chapter 15 module 2, ID m10260, I'll update in the body of the ticket as well

**Comment by lwtchu** [comment] 2021-06-23 21:01
looks like tabling styling got stripped out of this recipe for some reason. changing the title to reflect what is needed and updating original comment

**Comment by lwtchu** [comment] 2021-06-24 17:06
We need to change the span-all class to top-titled. This is a content fix. Closing.

Side note: default tables aren't available for this style. Confirmed with this search here for tables with no classes: https://openstax.github.io/sifter/#v=1&q=table%3Anot%28.span-all%29&code=&sourceFormat=xhtml

We can reopen if there's an issue but it appears all the tables should have a top-title.

**Closed by lwtchu** 2021-06-24 17:06 UTC
Labels: book:american.government.3e, prio:moderate, recipestyle:american-government, type:change.request
