### ISSUE TITLE
grey line at margin of list in baked Soc2e

### ISSUE THREAD

**Issue by oscryan** [openstax/cnx-recipes#770] opened 2019-01-09 18:52 UTC
# What happened?

A margin line shows up in some lists in Sociology 2e after baking.

# Reproducibility Details
- **Does this happen in one place, a few places, or everywhere?**: not everywhere

# Environment:

- **Book(s)**: Sociology 2e
- **URL/Server**: staging.cnx.org after bake
- **Location (page number, chapter/section)**: https://staging.cnx.org/contents/AgQDEnLI@14.1:JHjddfwj@5/1-4-Why-Study-Sociology
- **Suggested nearby searchable text**: an understanding of social systems and large bureaucracies;
- **Browser**: firefox

# Screenshots

<img width="531" alt="screen shot 2019-01-09 at 12 47 24 pm" src="https://user-images.githubusercontent.com/1895432/50921360-787b7d00-140d-11e9-8bf7-043dbff1e49e.png">

**Comment by helenemccarron** [comment] 2019-01-22 15:21
The list is in block-quotes. It looks a bit weird since this is just a list but behaving as intended/

**Comment by openstaxalina** [comment] 2019-01-22 20:40
Thanks so much for the investigation, @oscryan, @wilkus27, @Adrianltd, and @helenemccarron.  I am going to close this since we now understand that this list is displaying like this because of the block quote tag.

**Closed by openstaxalina** 2019-01-22 20:40 UTC
Labels: book:introduction.sociology.2e
