### ISSUE TITLE
Term index & polish diacritics 

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#1252] opened 2019-08-01 10:20 UTC
# What happened?
Diacritical marks ought to be ordered by polish alphabet.
# Reproducibility Details
- **Does it also happen in an incognito window?**: yes
- **Does this happen in one place, a few places, or everywhere?**: all 3 volumes, in index
- **Book(s)**: Fizyka dla szkół wyższych. Tom 1, 2, 3
https://katalyst01.cnx.org/contents/TqqPA4io@1.140:lyD6ZIjV@1.140/Skorowidz-rzeczowy
https://katalyst01.cnx.org/contents/FqtblkWY@2.175:HhU45nNF@2.175/Skorowidz-rzeczowy
https://katalyst01.cnx.org/contents/u2KTPvIK@3.32:BH43v6y2@3.32/Skorowidz-rzeczowy
![ŁŚĆÓ](https://user-images.githubusercontent.com/47241114/62285804-a7fbe080-b456-11e9-8dcf-545c643a41ee.jpeg)

**Comment by openstaxalina** [comment] 2019-08-12 14:21
This seems to be a duplicate of #1042; closing.

**Closed by openstaxalina** 2019-08-12 14:21 UTC
Labels: book:fizyka
