### ISSUE TITLE
Nursing Internal -- line break between assessment question and number in webview; bad alignment of question number in PDF  

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5462] opened 2024-02-14 14:40 UTC
# Summary & Screenshots

Assessment numbering alignment in PDF and Webview is not correct. See screenshots
Affects all nursing titles
Possibly related to #5458 

### Webview
![image](https://github.com/openstax/cnx-recipes/assets/89537088/5fbc9a56-b26d-468f-a2a1-2e26ae50a864)

### PDF
![image](https://github.com/openstax/cnx-recipes/assets/89537088/a80a21ad-5122-47eb-9b2a-9e77f1d30e9c)

# Sample Mark-Up
```
<!-- Paste CNXML here. -->
```

# Issue Occurrence(s)

 **Location**
- [x] In PDF
- [x] In Web

**Frequency**
- [x] At every instance of the content
- [ ] Irregularly
- [ ] Other (Please describe below)

# Content Location(s)
- **osbooks repo:** osbooks-nursing-internal-bundle
- **collection slug:** nursing-fundamentals
- **ref/branch:**
- **chapter/section:** All Assessments; See chapter 03
- **surrounding text:** 

# Acceptance Criteria

**Comment by lwtchu** [comment] 2024-02-14 17:39
Duplicate of #5458

**Comment by lwtchu** [comment] 2024-02-14 17:39
@Stackblocks I put this in CORGI Testing since the PR for the fix for this is tied to the other card but this has additional locations and examples

**Comment by lwtchu** [comment] 2024-02-26 20:30
Broke out second half of the card (PDF) to https://github.com/openstax/cnx-recipes/issues/5479 since it's a separate fix.

**Closed** 2024-02-27 16:24 UTC
Labels: prio:moderate, book:clinical.nursing, book:psychiatric.mental.health.nursing, book:fundamentals.nursing, book:maternal.newborn.nursing, book:medical.surgical.nursing, recipestyle:nursing-internal
