### ISSUE TITLE
Enable give-composites-ids Release Flag for Carnival Titles or All Titles 

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1794] opened 2020-01-22 19:18 UTC
# Scenario

To be able to link to composite pages, we need to enable the release flag `give-composites-ids` as listed here: https://github.com/openstax/cnx-recipes/blob/master/RELEASE_FLAGS.md

We should either enable for all Carnival books or potentially for all books if we can handle the testing now and get rid of that flag permanently.  

(For documentation, this card captures the other part of the work to enable linking to composite pages, which is already complete: https://github.com/openstax/cnx/issues/768.)

# Acceptance Criteria (required)

- [x] Flag is enabled on Carnival Theme books (minimally) or all books.
- [ ] We can generate PDFs for the Carnival Theme books using the CLI (or COPS once we merge to master again) and the Table of Contents includes specific page numbers and links to end of chapter and end of book pages.
- [ ] We have logged any regressions

# Test Plan

**Comment by Stackblocks** [comment] 2020-01-23 17:18
Enabled for all recipes in the Carnival theme:

- chemistry
- biology
- anatomy
- ap biology
- microbiology
- high school physics
- ap physics
- college physics
- university physics

@openstaxalina Can you provide a list of titles to be tested for this?

**Comment by openstaxalina** [comment] 2020-01-23 17:21
@Stackblocks woohoo!  What criteria should I use to compile this list?  All titles have composite pages.  Is there a precedent or reason that we would not test all of the titles?  

Thank you for your help!

**Comment by Stackblocks** [comment] 2020-01-23 17:25
@openstaxalina Basically a clearly defined list of all of the books that use recipes in the Carnival style. 

I wanted to make sure that Katalyst has an inclusive list of those books to check off as they test. I don't want to miss anything from not having a clear picture of the book - recipe correlation.

Thanks a million!

**Comment by openstaxalina** [comment] 2020-01-23 17:35
@Stackblocks got it.  Here is a list.  See note/question about _Fizyka_ at the end.

- [ ] Anatomy & Physiology
- [ ] Biology 2e
- [ ] Concepts of Biology
- [ ] Microbiology
- [ ] Chemistry 2e
- [ ] Chemistry Atoms First 2e
- [ ] College Physics
- [ ] University Physics Volume 1
- [ ] University Physics Volume 2
- [ ] University Physics Volume 3
- [ ] Biology for AP Courses (AP Bio)
- [ ] College Physics for AP Courses (AP Physics)
- [ ] Physics (high school) 
- [ ] Fizyka (it looks like this one may not have been enabled -- are we enabling flags for _Fizyka_ at this time?  It has its own recipe, separate from _University Physics_)

**Comment by Stackblocks** [comment] 2020-01-23 17:46
@wilkus27 Should I enable this for Fizyka as well? It doesn't appear in any of the other `enable-for()` lists, so i'm not sure if it's being handled separately.

**Comment by Stackblocks** [comment] 2020-01-23 17:51
# before
![image](https://user-images.githubusercontent.com/12678235/73009737-b956f180-3dd6-11ea-90fe-bac7264fa5e9.png)


# after
![image](https://user-images.githubusercontent.com/12678235/73009749-bd830f00-3dd6-11ea-84f2-2675a0d77594.png)

**Comment by MartaSztuka** [comment] 2020-01-29 14:44
Links and page numbers in ToC is fixed in following books:

- Anatomy
- Biology 2e
- Concepts of Biology
- Chemistry 2e
- College Physics
- AP Biology

**Comment by brittweinstein** [comment] 2020-02-13 16:06
I'll move this to the Icebox for us to get to when we handle the other titles.

**Comment by paulinaszczucinska** [comment] 2020-03-18 15:51
@wilkus27 this issue should resolve stale recipe problem #1876

**Comment by brittweinstein** [comment] 2020-05-01 15:13
@MartaSztuka can you confirm that this has been resolved?

**Comment by wilkus27** [comment] 2020-05-04 07:10
@brittweinstein we can't test it for now. There are still problems with baking polish u-physics on webview. Here is the link to thread in Slack about it: https://katalysteducation.slack.com/archives/CBW9DFKGF/p1588154877163100

**Comment by brittweinstein** [comment] 2020-05-15 18:48
@MartaSztuka please verify that this is working as intended for all books except for Fizyka. The CE Tech team is working on a fix to unblock the baking of Fizyka.

**Comment by brittweinstein** [comment] 2020-05-18 14:40
@MartaSztuka this should be unblocked now!

**Comment by brittweinstein** [comment] 2020-05-27 14:49
When we can successfully bake Fizyka, we can close this.

**Comment by MartaSztuka** [comment] 2020-05-29 07:51
Baking Fizyka went successfully, I'm closing the issue.
![Screenshot from 2020-05-29 09-37-04](https://user-images.githubusercontent.com/47241114/83235273-e9057400-a191-11ea-949d-41b040d79575.png)

**Closed by MartaSztuka** 2020-05-29 07:51 UTC
Labels: baked.styles
