### ISSUE TITLE
[Wait for WH Vol 1 Publish] World History - in webview, some words in heading are not bold

### ISSUE THREAD

**Issue by ww-openstax** [openstax/cnx-recipes#5054] opened 2023-03-17 12:05 UTC
# Brief Description of Scenario
In webview, `<term class="no-emphasis">` inside `<title>` causes the terms to be unbolded. 

![image](https://user-images.githubusercontent.com/89537088/225895777-30c0f800-3d2a-44e7-8227-1009fa68fcfe.png)

# Pattern of Occurrence 
every instance

# Acceptance Criteria
- [ ] title bolding should override the `<term class="no-emphasis">`
- [ ] other  `<term class="no-emphasis">` elsewhere should still not be bold
  
# Sample Mark-Up
```
<note class="beyond-book" id="note-00002">
    <title>The <term class="no-emphasis" id="term-00022">Iron Age</term> in Africa</title>
    <para id="para-00011">It had been thought that ironworking originated in modern-day Turkey ...</para>

```

# Location(s)
- **osbooks repo:** osbooks-world-history
- **collection slug:** world-history-volume-1
- **ref/branch:**
- **chapter/section:** Chapter 9 / Section 2; module m00095, line 32
- **surrounding text:**

**Comment by wilkus27** [comment] 2023-03-22 09:05
As I checked we are using two different approaches. In PDFs styles we have one selector: `[data-type="term"]:not(no-emphasis)` and we set bold for it, there is no separate styles for `[data-type="term"].no-emphasis` . On webview we are styling both things:

```
[data-type="term"] {
  font-weight: bold
}

[data-type="term"].no-emphasis {
  font-weight: normal
}
```

Styles for concrete selector are stronger, that's why on webview bold for parent selector (title) doesn't overwrite normal from no-ephasis .

I would say that more correct solution is on webview. We should use `no-emphasis` class to remove bold from things. If we need bold we should just remove class from the content. So actually it would be good to make fix for PDFs, but I'm afraid that we will have a lots of regression with cases like in this issue. That is, if `no-emphasis` is within elements with bold it won't inherit it, it will still be normal.

**Comment by MartaSztuka** [comment] 2023-03-23 09:44
There are more instances, when term appears in headers and figure/table caption.
#### Finance
###### Figure 4.2
![Screenshot from 2023-03-23 10-33-38](https://user-images.githubusercontent.com/47241114/227161767-b49d2497-6d0b-46f9-b683-2bec862b937d.png)
![Screenshot from 2023-03-23 10-27-43](https://user-images.githubusercontent.com/47241114/227160231-cf189a3e-7cc0-4188-94cc-80e6fd4a2d8b.png)

###### Table 15.6
![Screenshot from 2023-03-23 10-29-43](https://user-images.githubusercontent.com/47241114/227160956-76a6c422-b9e9-44ae-9075-24151252f1c8.png)
![Screenshot from 2023-03-23 10-31-41](https://user-images.githubusercontent.com/47241114/227161222-b00d001e-9950-427e-a226-1f8fc9d4b15d.png)

#### College Success
###### Netiquette header in 8.3 Communication and Technology
![Screenshot from 2023-03-23 10-35-44](https://user-images.githubusercontent.com/47241114/227162492-bd67af4a-6ec7-430d-92a2-3941dde0c6f7.png)
![Screenshot from 2023-03-23 10-37-42](https://user-images.githubusercontent.com/47241114/227162682-f45caf1f-57c5-435e-bd63-384b82a7e75f.png)

#### BCA
###### The Excel Ribbon header in 1.1 Microsoft Excel Basics
![Screenshot from 2023-03-23 10-39-17](https://user-images.githubusercontent.com/47241114/227163261-29ceb9c2-cde1-4502-8169-a86110643587.png)

**Comment by lwtchu** [comment] 2023-03-23 14:22
## Entrepreneurship (12 items)
[The Process of Becoming an Entrepreneur : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71122/index.cnxml#term-00061)
[The Process of Becoming an Entrepreneur : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71122/index.cnxml#term-00062)
[Growth: Signs, Pains, and Cautions : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71172/index.cnxml#term-00003)
[Growth: Signs, Pains, and Cautions : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71172/index.cnxml#term-00006)
[Growth: Signs, Pains, and Cautions : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71172/index.cnxml#term-00010)
[Growth: Signs, Pains, and Cautions : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71172/index.cnxml#term-00018)
[Building and Connecting to Networks : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71182/index.cnxml#term-00047)
[Building and Connecting to Networks : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71182/index.cnxml#term-00051)
[Building the Entrepreneurial Dream Team : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71183/index.cnxml#term-00027)
[Managing Resources over the Venture Life Cycle : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71194/index.cnxml#term-00019)
[Managing Resources over the Venture Life Cycle : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71194/index.cnxml#term-00021)
[Launching Your Venture : term.no-emphasis](https://github.com/openstax//osbooks-entrepreneurship/tree/main/modules/m71198/index.cnxml#term-00010)

**Comment by lwtchu** [comment] 2023-03-24 15:28
Moving this into a later sprint and iceboxing - we should probably go with the webview version of the fix, but we'll have to time it after the WH pdf publish

**Comment by wilkus27** [comment] 2024-02-07 09:25
Same as https://github.com/openstax/cnx-recipes/issues/5423

**Comment by lwtchu** [comment] 2024-02-12 15:34
Larissa to merge with the other issue

**Comment by lwtchu** [comment] 2024-02-13 15:47
@Stackblocks I'm going to put this into CORGI testing since it's tied with the other issue. The content should be correct in the instances above. I can help with testing when this goes out

**Comment by lwtchu** [comment] 2024-02-26 21:38
![Screenshot 2024-02-26 at 3 37 44 PM](https://github.com/openstax/cnx-recipes/assets/11299125/8cfe27d7-c47b-4331-b9fc-0ba10b19aa4f)
Still broken in Finance - Video Activity Ch 16

**Comment by lwtchu** [comment] 2024-02-26 21:39
![Screenshot 2024-02-26 at 3 39 23 PM](https://github.com/openstax/cnx-recipes/assets/11299125/e46fca96-b989-44fa-b708-ddc127752eb0)
but good here

**Comment by lwtchu** [comment] 2024-02-29 18:20
Card for Finance issue opened

**Closed by lwtchu** 2024-02-29 18:20 UTC
Labels: prio:moderate, book:world.history
