### ISSUE TITLE
Finance - Number list incorrect alignment in "Think it Through" section

### ISSUE THREAD

**Issue by srm-openstax** [openstax/cnx-recipes#4356] opened 2022-01-12 08:50 UTC
Hi Team,

Number list alignment in "THINK IT THROUGH" Section is incorrect please & reslove it.

![image](https://user-images.githubusercontent.com/86622862/149094352-38e1b03c-1c99-4798-9854-40f1570b9a6c.png)

![image](https://user-images.githubusercontent.com/86622862/149094299-967d61b3-8094-47c6-a977-95a78eade9f8.png)

# Bug Location(s)
collection ID: col00006
github openstax/osbooks- link: https://github.com/openstax/osbooks-intro-finance/
chapter/section: Chapter 13/Section 2
surrounding text:  "Find the sample variance and sample standard deviation by creating a table with three columns"

**Comment by wilkus27** [comment] 2022-01-20 14:10
Checked locally on current milestone branch. It's already fixed:

![image](https://user-images.githubusercontent.com/40228854/150354125-d2e6e786-00d8-4b47-859a-572e55848627.png)

@lwtchu can I close the issue or do you want me to move it to regression testing column, so it could be checked on released code version?

**Comment by lwtchu** [comment] 2022-01-20 17:37
sorry i didn't realize it was a duplicate of this #4327 - i'm closing

**Closed by lwtchu** 2022-01-20 17:37 UTC
Labels: book:introduction.finance, theme:cardboard
