### ISSUE TITLE
Different numbering of examples

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#847] opened 2019-02-14 15:52 UTC
1. In webview Examples starts with '0', in PDF starts with '1'.
2. In PDF after Example is 'Try it #number of the example' in webview is 'Try and following number'

https://katalyst01.cnx.org/contents/mwjClAV_@8.1:0KhpF2RH@23/1-1-Real-Numbers-Algebra-Essentials

Numbering in webview should be fixed to start with '1', also "try' section needs to be replaced with 'Try it # ex. number' as it is in PDF.

![ex w](https://user-images.githubusercontent.com/47241114/52798740-d63c5e00-3078-11e9-9f10-7dc1c09d9431.png)

![ex pdf](https://user-images.githubusercontent.com/47241114/52798754-db99a880-3078-11e9-996a-bcb6b2a1739a.png)

**Comment by Adrianltd** [comment] 2019-02-21 13:05
Duplicate of https://github.com/openstax/cnx-recipes/issues/846

**Closed** 2019-02-22 13:05 UTC
Labels: book:college.algebra, prio:high

**Comment by MartaSztuka** [comment] 2019-02-25 11:40
I'm closing (properly now) problem is solved, here's screenshot:
![screenshot from 2019-02-25 12-36-33](https://user-images.githubusercontent.com/47241114/53334950-7ce6f100-38fa-11e9-80be-f2af17432eba.png)
