### ISSUE TITLE
Symmetry Feedback: More Space with Multi-Line EOC Section Links

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1978] opened 2020-02-28 23:38 UTC
# Scenario

When there is a linked section header in EOC, and any of the characters goes below the line (like "y"), it runs into the line below:

![Screen Shot 2020-02-28 at 5 35 41 PM](https://user-images.githubusercontent.com/7863733/75595200-fe62e900-5a50-11ea-97ba-158ce00f365f.png)

![Screen Shot 2020-03-02 at 4 53 54 PM](https://user-images.githubusercontent.com/7863733/75725713-ac1b0580-5ca6-11ea-81ca-a71fd701d0a1.png)

![Screen Shot 2020-03-02 at 5 09 09 PM](https://user-images.githubusercontent.com/7863733/75726673-97d80800-5ca8-11ea-893b-a72ddcdcd211.png)

We should not add a ton of space here because that'll presumably impact all multi-line linked section headers and make the PDF longer.  What is the minimum amount of space we could add on the grid?

# Acceptance Criteria (required)

# Test Plan

**Comment by lwtchu** [comment] 2020-03-02 22:07
"font-family: Muli,
font-size: font-scale(3),"

^ Should we add a line-height attribute to this?

**Comment by ajluk** [comment] 2020-03-05 14:10
The spaces under sections links issue will be resolved in this PR: https://github.com/openstax/cnx-recipes/pull/2014. I have added line-height: line-height(3) to the section links titles to be consistent with fon-size: font-scale(3), but it seems to wide:
![image](https://user-images.githubusercontent.com/55203598/75988842-808c5b00-5ef2-11ea-8a47-3490f050d035.png)
I have also investigated why the space between each columns in the exercises got tighter and it is caused by `display: table` and `display: table-caption` properties set for Problem Wrapper and Problem Container. There is a separate issue related to this, created by Natalia (https://github.com/openstax/cnx-recipes/issues/1870) with proposal changes to exercises. It is also related with the general EOC cleaning issue: https://github.com/openstax/cnx-recipes/issues/1942#issuecomment-595227210

**Comment by ajluk** [comment] 2020-03-09 14:38
Changes in TDS:
Changes in this component: **EocSectionTitleLink** in all shapes including it: (**KeyEquationWithSectionLinks** l. 650, **SummaryWithSectionLinks** l.640, **EocCompChapExercises** l.668: ConceptCompChapPage, CriticalThinkingCompChapPage, ProblemsCompChapPage, PerformanceCompChapPage, MultipleChoiceCompChapPage, ShortAnswerCompChapPage, ExtendedResponseCompChapPage - l. 683, ConceptualQuestionsCompChapPage l.708, 
**EocSectionTitleLink**
changed properties:
font-size: font-scale(2), (changed from 3 to 2)
line-height: line-height(2), (new property added)

**ProblemsCompChapPageWithTwoColumns** (I couldn't find it in the table, maybe the whole shape needs to be added (under l.716):
**Container**
 margin-bottom: v-grid(2),
column-count: 2,
column-gap: 2.4rem,
column-width: auto,
**CompChapPageHeader**
font-family: (_ref: 'typography:::sansFont'),
font-weight: bold,
 font-size: font-scale(3),
line-height: line-height(3),
text-transform: uppercase,
column-span: all,
color: book specific: B5 for University Physics 
margin-bottom: v-grid(1)
**EocSectionTitleLink**
font-family: "Muli",
font-size: font-scale(2),
line-height: line-height(2),
**ProblemWrapper**
 display: table,
**ProblemNumber**
 color: (_ref: 'colorMap:::fontBodyColor'),
 font-weight: bold,
text-decoration: none,
display: table-cell,
ProblemDivider
margin-right: h-grid(1)
ExerciseOrderedList
margin-left: h-grid(4),
margin-bottom: v-grid(1),
ExerciseNestedOrderedList
margin-left: h-grid(2),
margin-bottom: v-grid(1),
ExerciseFigure
max-width: 100%,
),

AdditionalProblems, ChallengeProblems l.697):
EocSectionTitleLink
changed properties:
font-size: font-scale(2), (changed from 3 to 2)
line-height: line-height(2), (new property added)

component **SectionTitleLink** needs to be replaced with **EocSectionTitleLink** in shape **EocSectionSummary** l.612
with properties: 
font-family: "Muli",
font-size: font-scale(2),
line-height: line-height(2),
component **SectionTitleLink** needs to be replaced with **EocSectionTitleLink** in shape **EocConceptualQuestions** l.619
with properties: 
font-family: "Muli",
font-size: font-scale(2),
line-height: line-height(2),
component **EocSectionTitleLink** needs to be added to shape **EocProblemsExercises** l.628
with properties: 
font-family: "Muli",
font-size: font-scale(2),
line-height: line-height(2),
new component needs to added to **EocProblemsExercises** shape under l.628: **FigureUnderSectionTitleLink**
with properties:
 max-width: 100%,
 padding-top: half-v-grid(1),

**Comment by MartaSztuka** [comment] 2020-03-10 11:39
tested
![Screenshot from 2020-03-10 12-38-35](https://user-images.githubusercontent.com/47241114/76308994-2d3c5300-62cc-11ea-98be-80f49ded7545.png)

**Closed by MartaSztuka** 2020-03-10 11:39 UTC
Labels: baked.styles, book:college.physics
